### ISSUE TITLE
Dialog accepts undefined as false for open

### ISSUE THREAD

**Issue by toni-leigh** [Sage/carbon#1600]
We're finding that if we have a dialog on the page and we don't have a strictly Boolean default value available then we get a warning because `open` is undefined instead of Boolean.

An example of when this might happen is if you're waiting for an API response in `componentDidMount` and that response governs the open state of your dialog.

We have got round this by defaulting store data or using `|| false` in our dialog definition, but it might be a bit easier if Carbon just did it for us

**Comment by andrewjtait** [comment]
Maybe this is useful in ensuring your code is explicit and that you're not passing something unintentional. Your current solution (default in the store or in the component) sounds like the right solution.

**Comment by toni-leigh** [comment]
@andrewjtait Shouldn't something unintentional be caught by good tests?

Whereas doing this just means we need to add a new boilerplate test just to get coverage. It feels like repetitive work which could be covered by the library.

Would it be too bad to process `undefined` as falsey?

**Comment by andrewjtait** [comment]
An alternative could be to use `defaultProps` in your component to default the value to `false`. If your component is one that is using state through a connected store, then you could update to use the new `connect` function which means your component will be using props instead (though it sounds like defaulting it in the store is the best place).

If you're out of other options then doing `!!(open)` could be a last resort. With all the options available there must be one suitable enough that you can ensure it is a boolean. Otherwise there is no need in having the PropType validation either.
