### ISSUE TITLE
Error when using different locale with moment.js

### ISSUE THREAD

**Issue by andrewjtait** [Sage/carbon#1665]
moment.js throws an error if you try using a locale which you have not configured. For example if you use `fr` but have not included `moment/locale/fr`.

We should try and catch these errors and provide a more meaningful message to help developers, or default to the `en` locale which we automatically include.

**Comment by ianforster-sage** [comment]
FE-1790

**Comment by DipperTheDan** [comment]
FE-3472 will also address this issue.

**Comment by chrisbarber86** [comment]
I think we can actually just close this issue. it's more about Developer Experience than anything else and we will ultimately replace the usage of moment.js due to their recent announcement  

https://momentjs.com/docs/#/-project-status/

> However, since we understand that Moment is well established in millions of existing projects:
> We will address critical security concerns as they arise.
> We will release data updates for Moment-Timezone following IANA time zone database releases.

Admittedly replacing it is lower priority whilst they will continue to support timezone changes and critical security concerns.

We will continue to support issues using it whilst it's part of our codebase but I don't think we need to do any work around developer experience for it. If you try to use a locale you haven't configured, I think it's pretty fair to get an error back.

**Comment by sjohnson-sage** [comment]
Closing as per Chris' comment above
