### ISSUE TITLE
Changing tab changes the URL

### ISSUE THREAD

**Issue by mfolker-sage** [Sage/carbon#1887]
**Issue:**

When a tab is selected, the URL is changed by this code: https://github.com/Sage/carbon/blob/d872f938a67258669013bacdd8df954e0089e525/src/components/tabs/tabs.js#L337 
https://github.com/Sage/carbon/blob/d872f938a67258669013bacdd8df954e0089e525/src/components/tabs/tabs.js#L338

**Use case:**

This presents an issue when a react application returns "Fragments" from the render method of a component, which is something that you may wish to do in the absence of a routing engine, i.e. when serving the site out of S3, as a URL can only contain one '#' element.  

**Suggestion:**

Make this functionality optional.

**Comment by gusch** [comment]
Could you please correct this one asap because it crashes our project.

We have a combination of Asp.Net and React/Carbon and when a tab is selected, the url go from http://localhost:49413/.....?ctxKey=0b0455f9-2591-4e35-86fd-23c4391f9c7c to http://localhost:49413/...#1.

the ctxKey param is vital for our ASP part to work correctly

The suggestion made by mfolker-sage seems a good one for us.

Thanks in advance

**Comment by sianford** [comment]
Hi @gusch. Can you confirm that you're satisfied that this issue has been resolved in https://github.com/Sage/carbon/pull/2188 please? Thanks :)
