### ISSUE TITLE
Select component : Error if value set and no options

### ISSUE THREAD

**Issue by ardvi** [Sage/carbon#2566]
https://codesandbox.io/s/carbon-quickstart-7lw1l

To reproduce :
Put a Select component without option child, set a value to Select
> A error 'Cannot read property 'find' of undefined' throwed

**Comment by jamime** [comment]
# Scenario
> My options list are async loaded , so it’s possible that i can have the select value before the options. 

We need to consider if we want to support this, we should speak to UX to find out what the best pattern for this is. It may be that the entire Select should be conditionally rendered. 

We need to consider the experience when opening the select before the options have loaded.

**Comment by harpalsingh** [comment]
I wouldn't expect to click on a select and then wait for any options to load, there should be options pre-loaded or select disabled if it depends on something else to pre-populate the options. We have used lazy loading on selects when there is a large value, but that only happens when the initial list is handled, then you have the "type to search" where an input only shows options once a search has been actioned.

So if a select is used, it should have some values, otherwise if its a search field that then returns results, only then would the options be loading dynamically.

I'll try to find some designs and/or put some updated concepts on these patterns into the DLS.

**Comment by harpalsingh** [comment]
Currently, if the "search" method, there is not loading text/animation, just dropdown shown if results are found.

**Comment by jamime** [comment]
> We have used lazy loading on selects when there is a large value, but that only happens when the initial list is handled

Do we have designs for this in the DLS? e.g. when is the data loaded (on click?) and is there a loading state of the component while the user waits for the data to come back? The latest version of the component doesn't support this, which is the issue that was raised by Sage 100 and Sage 200.

**Comment by jamime** [comment]
We had an internal meeting regarding this and decided that the Select component will remain as a dumb component.

For more advanced use cases UX will be creating examples that give a better user experience.

In order to pre-select a value, you **MUST** have it as an `<Option>` within the `<Select>`.
