### ISSUE TITLE
DialogFullScreen component, className isn't taken into account

### ISSUE THREAD

**Issue by arvig33** [Sage/carbon#2645]
### Current behaviour
With a DialogFullScreen component, if a className property is defined, it's not taken into account.

### Expected behaviour
With A DialogFullScreen component, if a className property is defined, the component must take this into account..

### Reproducible example
https://codesandbox.io/s/vibrant-moser-n91dy
the scss file is not applied.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 13.2.0
| carbon-factory   | -
| react-scripts    | -
| React            | 16.8.7
| Browser          | Chrome / Firefox
| npm              | 6.13.7
| Operating System | Windows 10 Enterprise

**Comment by jamime** [comment]
Hi @arvig33,

Please can you explain why you need this?

We're adopting style objects in some components. Generally, we want to prevent users from writing styles because they often rely upon the component's internal interface (DOM structure, attributes or class names). This has caused some consumers significant upgrade problems (v8-v9 for example).

If there is a style change that you need to make, we would typically run this via our UX team and merge it into the DLS/carbon.

**Comment by ianforster-sage** [comment]
This issue has been closed because it has not had recent activity. If you believe this issue is still valid and required please reopen it. Thank you for your contributions.
