### ISSUE TITLE
Drawer component: Sidebar is not positioning elements at the top

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#2918]
### Current behaviour

The sidebar in the Drawer component has a margin top applied and causes misalignment with the right hand side.

### Expected behaviour

I'd expect to see the heading in the sidebar inline with the heading in the right hand side.

### Reproducible example

https://codesandbox.io/s/sad-moore-rfqjv?file=/src/index.js

### Suggested solution(s)

Looks like the margin top of 60px is causing this issue.
https://github.com/Sage/carbon/blob/master/src/components/drawer/drawer.style.js#L9

I think there does need to be some consideration that any content that was to reach the chevron would be wrapped?

### Additional context

Initial designs have the chevron hidden

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 19.0.0
| carbon-factory   | N/A
| react-scripts    | 3.4.1
| React            | 16.13.1
| Browser          | All
| npm              | 6.14.4
| Operating System | Mac

**Comment by jamime** [comment]
FE-2790

**Comment by damianOfKyan** [comment]
Hi @philearley , margin top is there for a reason so that Sidebar content does not get in the way of close/open chevron icon when drawer expands or collapses.

If you really want to bring the content of sidebar up you can do so by use of `position` and `top` css properties.

Here is your example which I updated so that content of sidebar has same horizontal position as content.

https://codesandbox.io/s/happy-cannon-or3tw?file=/public/index.html
