### ISSUE TITLE
Switch in error with labelInline and reverse=false

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#3022]
### Current behaviour
If I use a switch in Formik/Form component with the props labelInline and reverse={false}, i have this :
![image](https://user-images.githubusercontent.com/16415182/85744361-21eb2700-b705-11ea-9d6c-c087a9c19fe5.png)

### Expected behaviour
The label and the error icon shouldn't collide.

### Reproducible example
https://codesandbox.io/s/carbon-formik-yup-egjlt?file=/src/index.js

**Comment by jamime** [comment]
@harpalsingh do we still want to support having the label on the right? I think this is from the classic implementation.
DLS currently shows label above or to the left.

**Comment by jamime** [comment]
> the icon should push the text over in that scenario
-- Harpal

**Comment by sjohnson-sage** [comment]
@jamime @harpalsingh if the icon just pushed the text over it still wouldn't work as the tooltip over the error icon would go over the text: 
![image](https://user-images.githubusercontent.com/14963680/89890315-09f33800-dbcb-11ea-9189-9c7d726ddc5a.png)

Should the icon be after the text instead?

**Comment by gusch** [comment]
The icon is after the text for a Checkbox

![image](https://user-images.githubusercontent.com/16415182/89899421-92c99e00-dbe2-11ea-973a-50d7feae0419.png)

**Comment by sjohnson-sage** [comment]
If you need a workaround for this @gusch you can set the validation on the label instead of the component. Go to https://carbon.sage.com/?path=/story/experimental-switch--validations and set `labelInline` to true and `reverse` to false and look at the "On label" story:

![image](https://user-images.githubusercontent.com/14963680/89900798-1af87500-dbdc-11ea-9da9-9aed9b61062c.png)
