### ISSUE TITLE
Multiple pods placed horizontally don't size themselves to the height of the largest contents

### ISSUE THREAD

**Issue by StevenMWood** [Sage/carbon#3046]
### Current behaviour
Multiple pods that are placed horizontally to each other size themselves to the height of their contents.

### Desired behaviour
Allow the pods to size themselves to the largest height of the pods in the row so that the top and bottom edges line up on the form, which looks much better from a presentation perspective.

### Suggested solution
Allow adjacent pods to size themselves to the largest content height.

### Describe alternatives you've considered
None

### Additional context
None

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 24.0.1 |
| react-scripts    | 3.0.1|
| React            | 16.8.6 |
| Browser          | Chrome |
| npm              | ? |
| Operating System | Windows 10 |

**Comment by ianforster-sage** [comment]
Pod heights – could be a good option for visual tidiness. Would we want behaviours like this [flexbox](https://codepen.io/rachelandrew/pen/ZOpXEM) example? (other solutions may be better technically, but the effect looks good). - Ben Wilson

**Comment by benwilsonsage** [comment]
Suggested spec:

Config: "equalHeight"
- Where there is more than 1 Pod in a given container, this config will make the height of all cards match the height of the tallest Pod, so that all Pods have equal height.
- Without this config, each pod independently takes the natural height of their contents, plus any padding set.

This might be achieved using Flexbox, display:table, or whatever technical means is best.

![equalHeight](https://user-images.githubusercontent.com/12499090/87708654-f8209f80-c79a-11ea-866b-90b5f648894f.png)

**Comment by StevenMWood** [comment]
Codebox sample from my team to demonstrate the problem.
https://codesandbox.io/s/pods-do-not-fill-parent-row-height-8ujmn?file=/src/component.js
