### ISSUE TITLE
AppWrapper has minimum width CSS styling which cause truncation

### ISSUE THREAD

**Issue by StevenMWood** [Sage/carbon#3047]
### Current behaviour
The AppWrapper component has a minimum width CSS styling on it which means that full width forms, when displayed on an iPad, have right aligned buttons cropped off the edge of the screen.

### Expected behaviour
Right aligned buttons should be displayed without being cropped on the screen when the form is displayed on an iPad.

### Reproducible example
Simple version showing problem with right aligned buttons with placeholder menu container:
https://codesandbox.io/s/elated-sutherland-tcjvj?file=/src/index.js

### Suggested solution(s)
Remove or reduce the minimum width styling on the AppWrapper component to allow it to work on iPads
 
### Additional context
None.

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 24.0.1 |
| react-scripts    | 3.0.1|
| React            | 16.8.6 |
| Browser          | Chrome |
| npm              | ? |
| Operating System | Windows 10 |

**Comment by jamime** [comment]
@StevenMWood please can you provide a reproducible example, without one we'll be unable to check that any potential solutions meet your requirements.

**Comment by StevenMWood** [comment]
> @StevenMWood please can you provide a reproducible example, without one we'll be unable to check that any potential solutions meet your requirements.

I have updated the original bug with a code sandbox example.

**Comment by ianforster-sage** [comment]
At the moment the Sage Design System only supports a min-width of 960px. Further responsive or adaptive support will require design input. We'll refer this to UX.

**Comment by benwilsonsage** [comment]
Here's a reference on grid and breakpoints: There are some breakpoints outlined here: http://designsystem.sage.com.s3-website.eu-central-1.amazonaws.com/foundations/grid/

Would the following work?

Breakpoints (measured in dp) | Device Type | Margins | Gutters
-- | -- | -- | --
Extra Small (320px) | Smart Phones | 16px | 16px
Small (600px) | Portrait Tablets | 24px | 16px
Medium (958px) | Landscape Tablets & Low-Res Laptops | 32px | 24px
Large (1260px) | High-Res Laptops & Monitors | 40px | 24px
Extra Large (1921px) | Ultra High-Res Monitors | 40px | 24px

I've suggested 958px rather than 960px to support legacy accounting.
The developer could choose one or more breakpoint depending on their needs.

**Comment by jamime** [comment]
> I've suggested 958px rather than 960px to support legacy accounting.

As accounting is using the classic theme and there is no upgrade path from v8 to v9 I think we can use the default 960px.

**Comment by ianforster-sage** [comment]
We are discussing requirements for changes to our layout Grid with UX soon, I'll add this issue to the agenda and report back once we have a way forward.

**Comment by ianforster-sage** [comment]
Grid component enhancements now agreed by UX FE-3025 raised on backlog

**Comment by ianforster-sage** [comment]
Grid component enhancements were released in v41.0.0. https://github.com/Sage/carbon/releases/tag/v41.0.0
Closing this issue as resolved.
