### ISSUE TITLE
Bring back Dialog.renderChildren method

### ISSUE THREAD

**Issue by akuji1993** [Sage/carbon#3373]
## Feature request
In https://github.com/Sage/carbon/commit/ee8532adf56ebf897b0df86fc7c0ed00848fc54f#diff-3a9c458f3f4d7ed5abf46c8ab72911f633542ad3c15dfdde89c26106c03b2329 you removed the method renderChildren because it wasn't needed to check for a Form component in the Dialog. However, I'm working with a Sage team and we're overwriting this method in our code to do other things with the children before rendering them. Removing this method has removed that way of handling things in our code completely. We only realized this issue now, as we still had the typings file provide the method for us (in theory). 

Please reimplement the method, even if it's not doing more than just returning props.children in the base component so we can get our overwritten methods working again. 

### Current behaviour
Currently, overwritten renderChildren methods are not recognized by the base class and therefore do nothing anymore. 

### Desired behaviour
Dialog should again have a renderChildren method that just returns props.children and can therefore be overwritten when needed.

### Suggested solution
Reimplement renderChildren 

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react|47.0.0|
| react-scripts| 3.4.3 |
| React |16.12.0|
| Browser | any |
| npm | 6.14.6 |
| Operating System | Windows

**Comment by SAHesse** [comment]
I agree with @akuji1993, please fix this.

**Comment by jamime** [comment]
Hi @akuji1993 @SAHesse, thanks for raising this issue.

`renderChildren` is not defined as a `propTypes` nor is it in the `d.ts` as such, it's considered an internal method. It was introduced in https://github.com/Sage/carbon/commit/199cebe2f0f1cf1087c8d12d17341cda0536d34e. It's highly likely that we will refactor this further to be a function component, at this point you won't be able to extend the class. This is true for all of our class components.

We suggest that consumers use composition instead of inheritance. There is good information about this on the [react documentation](https://reactjs.org/docs/composition-vs-inheritance.html#so-what-about-inheritance).



Inside of the carbon codebase we have "legacy" components that use class inheritance and we've found the maintainability of these components to be poor. Now that react supports hooks and function components we can achieve the same benefits without the maintenance overhead.

In terms of `Dialog` based on the information you have provided, you could achieve the same by doing the following

```js
const renderChildren = () => {/*TODO*/};
const MyDialog = ({children, ...props}) => <Dialog {...props}>{renderChildren(children)}</Dialog>
```

**Comment by akuji1993** [comment]
Hi @jamime we managed to solve it the way you suggested.

Another question though: We're using our own typings as we couldn't find a @types/carbon-react entry. I'm reading your comment like there actually IS an official typings source. Can you point me to that? Can we use that in our independent project?

**Comment by jamime** [comment]
I'm glad that solution worked for you 🙂 

The types are included inside of the `carbon-react` lib, they're not available on all components but we continue to add more. They should work without any additional setup required, just import the component.

Here is an example https://github.com/Sage/carbon/blob/master/src/components/button/button.d.ts

If you have some types that we are missing we'll happily add them (as long as they are complete) if you submit a PR.

**Comment by sjohnson-sage** [comment]
Closing as per above comments
