### ISSUE TITLE
Default DateRange value as empty

### ISSUE THREAD

**Issue by limcoc** [Sage/carbon#3501]
### Current behaviour
Date Range Component always displays a date even when default value is set as ['', '']. While setting a blank defaultValue does make the formattedValue empty, visually, a date is still displayed and the rawValue remains as today's date.
https://carbon.sage.com/?path=/docs/experimental-date-range--default-story

### Desired behaviour
I am currently using the date range component to perform some optional filtering. By default I want the field to display as empty and have an empty rawValue.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 48.7.1 |
| React            | 16.14.0 |

**Comment by jamime** [comment]
I've confirmed this issue. There is a way to pass props to the individual `Date` inputs (`allowEmptyValue`), but in this case it has no effect.

```js
<DateRange
        startDateProps={{
          allowEmptyValue: true
        }}
        endDateProps={{
          allowEmptyValue: true
        }}
        startLabel="Start"
        endLabel="End"
        onChange={handleChange}
        value={state}
      />
```
It appears to be caused by this, where the date defaults to todays date.
https://github.com/Sage/carbon/blob/dbbbda5e94713a001fef2b5eba344ce2f7500a57/src/__experimental__/components/date-range/date-range.component.js#L23-L32

**Comment by ianforster-sage** [comment]
FE-3462
