### ISSUE TITLE
eslint Error for Link component in jsx file

### ISSUE THREAD

**Issue by hagad** [Sage/carbon#3581]
### Current behaviour
If we put a link component in the jsx file => it gererates an eslint error.
`Anchor used as a button. Anchors are primarily expected to navigate. Use the button element instead. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md`
`Link hasOnClick onClick={() => {}}> This is a link </Link>.`

For the moment i added 

`{ /* eslint-disable-next-line jsx-a11y/anchor-is-valid */}`

### Reproducible example
Add a link in jsx file : 
`Link hasOnClick onClick={() => {}}> This is a link </Link>.`

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 56.1.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sjohnson-sage** [comment]
Hi @hagad could you provide more detail about your usage of `Link` here please, are you using it with an `href` prop as well? Maybe using a `Button` component would be more appropriate depending on the use case

**Comment by hagad** [comment]
@sjohnson-sage  with href it doens't work, for my case i have to use the onClick to do some actions :
        ```
  <Link
            hasOnClick
            onClick={() => {
              actions1
              actions2
              actions2
            }}
          />
```
If a use Button the design is not good. 
The problem is an eslint error for jsx. and i don't think changing the lint configuration is the best way

**Comment by sjohnson-sage** [comment]
Hi @hagad - I'll add this to our backlog to sort. It should be rendering the link as a `button` element, not an `a` when the `onClick` prop is there (without `href`) so this lint error shouldn't happen

**Comment by sjohnson-sage** [comment]
FE-3693

**Comment by bulaj** [comment]
Hi @hagad, investigation revealed that this issue could be caused by default config values for `jsx-a11y/anchor-is-valid`:
https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md#rule-details

To my understanding there are two possible workarounds:
1. Import Link component under different variable name:
`import ActionLink from '...';`
`<ActionLink hasOnClick onClick={() => {}}> This is a link </ActionLink>.`
This should not trigger the warning.
2. Change eslint configuration for this rule, for example:
`    "jsx-a11y/anchor-is-valid": ["error",
      {
        "components": ["a"],
        "aspects": ["noHref", "invalidHref", "preferButton"]
      }
    ],`
    
Changes in our Link component code have no impact on this warning.
