### ISSUE TITLE
Change Height in TextEditor component

### ISSUE THREAD

**Issue by domy-sage** [Sage/carbon#3632]
Currently I am working in a UI POC of a service that we are doing in Collaboration (Messaging)

For this UI, the mockup looks like this: 

(image removed) 

**At this moment we cannot replicate this mockup because the TextEditor component has a fixed min-height.**

Besides the height issue, when an user fills all the main text box this grows moving the toolbar and buttons down. This, again, conflicts with behavior requested (textbook will grow in height, not moving the toolbar or buttons)

Let me know what you think about this, 

Thanks

**Comment by ianforster-sage** [comment]
I have removed the product specific screen grab from this issue. I'll DM the author.

**Comment by ianforster-sage** [comment]
I've asked DS squad for guidance on this.

**Comment by MarkMizenSagecom** [comment]
The designers say thanks for reaching out on this 👍 
 
The rich text editor is not currently in the design system. It's been agreed that it's going to be added, but we haven't started work on it yet.
 
That said, we see no reason that it shouldn't have a customizable minimum height, expanding as the content (including images, or link previews) requires.

We recommend that the minimum height is set in terms of rows of text rather than px (similar to the rows attribute on a textarea element). We need to do more research as part of adding the component to the design system, but for now we would recommend the lower limit of the minimum height be 2 rows of text.

**Comment by jamime** [comment]
FE-3692
