### ISSUE TITLE
Tab order for confirm dialog buttons

### ISSUE THREAD

**Issue by MarkMizenSagecom** [Sage/carbon#3713]
### Current behaviour

When using the confirm component the secondary button has a higher tab order than the primary button.
This means that when opening the component users automatically have the "No" option focused by default.

![Screenshot 2021-02-16 at 11 44 42](https://user-images.githubusercontent.com/55100780/108058756-6472c280-704c-11eb-9cb3-42f85cf19bfd.png)

### Expected behaviour
As the primary action is the "Yes" option, it should come first in the tab order, so as to match the visual hierarchy of the page. This should not overwrite the users tab location as the dialog could have focusable content within it.

### Reproducible example
https://carbon.sage.com/?path=/story/confirm--default-story

### Suggested solution(s)

Swap the order of the buttons in the confirm component: https://github.com/Sage/carbon/blob/d1c72c1aecede2d228ed03aabd8a4f795c83dba1/src/components/confirm/confirm.component.js

Change the parent to use `flex-direction: row-reverse`.

https://github.com/Sage/carbon/blob/d1c72c1aecede2d228ed03aabd8a4f795c83dba1/src/components/confirm/confirm.style.js#L7
```js
export const StyledConfirmButtons = styled.div`
  margin-top: 48px;
  display: flex;
  flex-direction: row-reverse;
  justify-content: flex-end;
`;
```

### Additional context
In general the order of the markup should match how it is output onto the page. In this case, the right hand button is more prominent than the secondary button, so sighted users use this component like so:

![image](https://user-images.githubusercontent.com/55100780/108060082-51f98880-704e-11eb-8e25-711b92d526ad.png)

This is also how we **want** users to interact with the element, so the markup makes semantic sense.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | latest |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by MarkMizenSagecom** [comment]
@harpalsingh  @tempertemper I would be interested in your opinion on this issue.

**Comment by harpalsingh** [comment]
@MarkMizenSagecom I think there are few key things that come into play here:

1.  We used to make primary left/secondary right, but decision was made to switch that order (Ben might have a better idea why I think it was just general team preference)
2. When a confirm or any dialog is fired, would we want the user to actively choose the "primary" option, as that will have a consequence, whereas the cancel does nothing, so accidentally pressing Enter doesn't trigger the confirm primary action.
3. From an accessibility POV if they meant to cancel, is it ok to expect Shift+Tab to go back or arrow key in this scenario?

Would be good to open up a chat with Martin Underhill too and discuss the options cause you make a valid question 👍

**Comment by ianforster-sage** [comment]
@tempertemper please could you comment on this when you have a minute.

**Comment by tempertemper** [comment]
Hi all, the tab order should reflect the visual order on the page, so if we were to flip the tab order only, we'd have a mismatch with the visual order.

If the order is incorrect, the solution would be to flip them visually so that the primary button comes first in the visual left-to-right order, and let the tab index take care of itself.

But as @harpalsingh says, the decision to flip the order may have been deliberate (@benwilsonsage do you have any background on this?). I imagine (but have no actual info) the rationale was something along the lines of 'no' being less destructive in (I'm speculating again) common use cases like "Are you sure you want to delete this thing?".

Note: I'm referring to the [Focus Order success criterion](https://www.w3.org/TR/WCAG21/#focus-order), which says: 

> when users navigate sequentially through content, they encounter information in an order that is consistent with the meaning of the content

This is a wee bit open to interpretation so I see where @MarkMizenSagecom is coming from: the visual weighting of the 'yes' button gives it more prominence, and it could be argued that that affects the meaning of the content, but that relies on styling trumping reading/source order, which I'd argue it doesn't as styling is (essentially) a progressive enhancement can be, for example, overridden or ignored by the user's browser settings.

**Comment by benwilsonsage** [comment]
Hi all - the Design System guidance on Forms says this right now... 

Button Order: In a button pair, 'Cancel' goes on the left, and 'Save' goes on the right - a consensus of surveyed third party Design Systems does it this way (with Windows being a rare exception). Although Nielsen (2008) says "(neither) choice is likely to cause usability catastrophes".

We're due to discuss this in the Forms task force shortly, but the cost and inconsistency of changing approach is probably high.

The approach has the benefit that the dialog 'ends' with a positive conclusion, but the disadvantage that users must tab past the negative action to get to the positive.

I see the difficulty with that, but suggest that tab sequence following reading order (top-to-bottom, left-to-right) might be best.

**Comment by ianforster-sage** [comment]
Based on the discussion above I'm closing this issue. Should you change the guidance in the DS please feel free to raise it again.
