### ISSUE TITLE
[Heading] cannot be styled using className

### ISSUE THREAD

**Issue by stripeyjumper** [Sage/carbon#3823]
### Current behaviour
Heading component cannot be styled using className

### Expected behaviour
className prop should be applied to the Heading wrapper div

### Reproducible example
https://codesandbox.io/s/smoosh-pond-z2tz0?file=/src/index.js

### Suggested solution(s)
Add the className prop to the heading wrapper

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 66.11.1
| react-scripts    | 3.4.4
| React            | 16.8.3
| Browser          | Chrome
| npm              | 6.14.4
| Operating System | MacOS

**Comment by sjohnson-sage** [comment]
Hi @stripeyjumper - we are actually removing the `className` props from our components, and we strongly discourage using them to write custom CSS where they still exist. 

You should rarely need to write custom CSS over a Carbon component, but if you do, we recommended using a styled-component to do so.

Having said that this is still a bug as the `className` prop is documented on `Heading` but not actually used in the component. The solution will be to remove the prop from the documentation.

**Comment by sjohnson-sage** [comment]
FE-3967

**Comment by stripeyjumper** [comment]
Hi @sjohnson-sage , thanks for that - the scenario is a custom centred header.  We can work around with a parent wrapper component, but it would be nice to be able to style directly with `styled(Header)`, which requires a `className` prop to be passed through.

**Comment by sjohnson-sage** [comment]
Thanks for clarifying @stripeyjumper - really the idea of Carbon is that users should never need to write custom styling over the components

`Heading` is due to have the styled-system margin props added to it (as some of our other components already have) so if it's the whole component you need to be centred - it will be achievable through those margins. If it's just the actual heading text you need to be centred, we can convert this issue to a feature request to add in an option to centre the heading via props

Let me know which scenario is appropriate and we can go from there

**Comment by stripeyjumper** [comment]
I think a prop to centre the alignments of all the text in the component would be the most useful to us.

Also, the `Typography` component might actually be a better match for what we're doing - it was added after our existing screens were created.  Not sure about alignment options there though!

**Comment by sjohnson-sage** [comment]
This was addressed by this PR https://github.com/Sage/carbon/pull/3920 and fixed in Carbon 68.25.3
