### ISSUE TITLE
Manage the position of error tooltip

### ISSUE THREAD

**Issue by loeliarigault** [Sage/carbon#3864]
## Feature request
Need to manage the display of an error message tooltip (on the top for the moment but maybe it's better to manage all position ?).

### Current behaviour
The ability to define the position of the tooltip isn’t available, it automatically renders to the right and only repositions when there is no space.

### Desired behaviour
Be able to set the display of a tooltip error for components.
ex : 
![image](https://user-images.githubusercontent.com/60605396/113003130-b857e780-9172-11eb-99e2-5556506e980a.png)

### Suggested solution
To have a property to set the display.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 68.5.0
| React            | 16.13.1
| Browser          | Chrome
| npm              | 6.14.2
| Operating System | Windows 10

**Comment by ianforster-sage** [comment]
@harpalsingh do you want us to surface this default position control on the Tooltip?

**Comment by harpalsingh** [comment]
Since we allow Tooltips to be positioned, would this not be a case on surfacing the same interaction? https://carbon.sage.com/?path=/story/design-system-tooltip--positioning There is a standard pattern, but of course designs can add scenarios where we need different positioning, so allowing that control could be useful.

**Comment by nicktitchmarsh** [comment]
I have raised FE-4074 for this issue
