### ISSUE TITLE
TileSelect object as value

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#4295]
### Desired behaviour

On an ordinary select [I can use objects as values for the options](https://carbon.sage.com/?path=/docs/design-system-select--default-story#with-object-as-value). I would like this to also be possible for TileSelects too.

### Current behaviour

[TileSelect value property only accepts strings](https://carbon.sage.com/?path=/docs/design-system-tile-select--default-story#tileselect-1).

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
Hi @liam-cochrane, 

We intended to remove this functionality when we re-wrote the Select component. However, we had several consumers who required this behaviour in their existing products.

We'd like to avoid adding this to any more components because it increases the complexity of the carbon library and can make consumers code more difficult to understand. We try to keep our components as close as possible to the HTML equivalent which is why it only accepts a string.

Ive outlined a few potential solutions, and some approaches that won't work.

The simplest of solutions is to look up the value using an object, like this:
https://codesandbox.io/s/gh-4295-kos3i

Alternatively, 
- You could use the event to access a `data-` attribute. This means the data object would be written to the DOM so it will need to be serialisable.
- You could use a ref to access the DOM to access the `data-` attribute. However, the `TileSelect` components don't forward refs.
- You could also write a wrapper component that uses context to build the data object when the `TileSelect` components are rendered. However, the `RadioButtonMapper` doesn't account for the `value` being an object. 

Please let me know if there's something that we haven't considered. 
Thanks,
