### ISSUE TITLE
Can't tab select checkbox in Safari

### ISSUE THREAD

**Issue by maspychaj-sage** [Sage/carbon#4324]
### Current behaviour

Can't select with Tab key checkbox field in Safari browser.

To reproduce click first input and then hit Tab key - in Safari it goes to second input instead of checkbox field.

### Expected behaviour

It's possible to select checkbox by hitting Tab in Safari - the same as in other browsers.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/cocky-hopper-ntsi7?file=/src/index.js

### Carbon Version

81.2.2

### What browsers are you seeing the problem on?

Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
Thanks for raising this @maspychaj-sage 

This is controlled by the OS and by Safari. Carbon does not standardise this across browsers in order to match users expectations, i.e. Safari users wouldn't expect these items to be highlighted unless they used Option + Tab.

I've added a screen recording showing how you can enable the same behaviour as Chrome.

https://user-images.githubusercontent.com/2328042/130619129-3421ab64-ef54-49de-b88c-09140d189d31.mov

It's also controlled by this system setting, which might also need checked depending on your version of MacOS/Safari.

![image](https://user-images.githubusercontent.com/2328042/130618564-c289be84-eec0-42ec-a5b4-4fd635847249.png)

Thanks,
Jamie
