### ISSUE TITLE
MultiActionButton and SplitButton backtabbing is not working as expected

### ISSUE THREAD

**Issue by LiliyaGi** [Sage/carbon#4352]
### Current behaviour

1) Not able to move to parent, sub-menu closed after pressing shift + tab but no focus on any elements

### Expected behaviour

1) shift+tab puts a focus on the parent for MultiActionButton and SplitButton

### CodeSandbox or Storybook URL

https://codesandbox.io/s/loading-spinner-for-export-forked-xjxml?file=/src/index.js

### Carbon Version

77.14.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS, Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-4322

**Comment by DipperTheDan** [comment]
Hi @LiliyaGi, 

Just letting you know that I've split this issue in to two separate tickets. The bug referring to the VoiceOver issue is #4372. Doing this makes it easier for us close each issue once the work has been completed. 

Thank you 😃

**Comment by tempertemper** [comment]
There is some inconsistency with the keyboard behaviour between these two components. They both share some functionality:

- Tabbing to the button triggers the dropdown
- Tabbing when focus is on the button takes focus to the next control (button, link, form field), skipping the dropdown element
- Pressing the down or up arrow key places focus on first or last item in the dropdown, respectively
- Pressing <kbd>tab</kbd> when focus is in the dropdown
- Pressing <kbd>tab</kbd> when focus is in the dropdown and on any item other than the last one loses focus
- Pressing <kbd>tab</kbd> a second time when focus has been lost puts focus back on the MultiActionButton trigger
- Pressing <kbd>tab</kbd> when focus is in the dropdown and on the last item takes focus to the first control on the interface

So there looks like a couple of bugs here:

- When tab is pressed on the last item. It shouldn't take focus to the first control on the page; rather it should take focus to the next control on the page
- When tab is pressed on any item but the last, it shouldn't lose focus; rather it should take focus to the next control on the page

The differences highlighted with <kbd>shift</kbd>+<kbd>tab</kbd> are also there:

- Pressing <kbd>shift</kbd>+<kbd>tab</kbd> when focus is in the MultiActionButton dropdown moves focus to the *SplitButton* trigger button; this should take focus to the MultiActionButton trigger button for consistency with the SplitButton component, although when the MultiActionButton is removed from the page, it behaves as expected, so this may just be a bug rather than functional
- Pressing <kbd>shift</kbd>+<kbd>tab</kbd> when focus is in the SplitButton dropdown moves focus to the SplitButton trigger button

At a more zoomed out level, we have a bigger issue here where this behaviour should be brought in line with the latest behaviour in the navigation, where if an item has a dropdown:

- It is triggered with a click/tap/<kbd>enter</kbd>/<kbd>enter</kbd> to level the playing field for pointer, touch, keyboard, and screen reader users
- An action/link on the trigger item (applicable to MultiActionButton) is moved into the dropdown list, leaving the trigger as a single purpose "Show actions" (but better content than that!) menu

But that's another job for another ticket!

**Comment by mrtn-a** [comment]
Hello, I wanted to follow up on this issue, are there any updates please :)?
