### ISSUE TITLE
Truncate Field Titles When Length Exceeds Container Width

### ISSUE THREAD

**Issue by shavonne-sage** [Sage/carbon#4500]
### Desired behaviour

As a Carbon user, I would like to disable field title wrapping so that long field titles do not force fields to appear further down on pages.

### Current behaviour

![image](https://user-images.githubusercontent.com/64958726/138058002-6cc8e7cf-8b21-4d04-a936-04b207c0dd35.png)

### Suggested Solution

![image](https://user-images.githubusercontent.com/64958726/138058620-750b854c-8856-4289-9c2b-e8db9fe7b782.png)

- when flag is set, field title is truncated and tooltip is provided to view full title

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tempertemper** [comment]
Truncation is a tricky one… Wrapping form labels ensures all users can access the content.

The tooltip solution has a few of downsides:

- It's only available to users with a pointing device (like a mouse or trackpad)
- It's not easily discoverable (i.e. it's not standard behaviour and there are no affordances other than the truncated label to tell the user it's there)
- It covers other page content

I would steer you away from the truncation. Sometimes to be accessible to all users, things have to be uglier 😞

**Comment by nicktitchmarsh** [comment]
@tempertemper & @ljemmo, given that DS is moving away from Carbon tooltips anyway, should we provide the title attribute on labels in the case of needing to truncate the content?

**Comment by ljemmo** [comment]
@nicktitchmarsh i'll defer to martin on this one for the overall say on truncation from an accessibility perspective. My gut feel is that we shouldn't be allowing truncation on fields - rather the field is working as intended in an accessible way.

@shavonne-sage please could you provide an example of the design where you feel this is needed so we can review in more detail?

**Comment by shavonne-sage** [comment]
@ljemmo , there are two field titles truncated on this screen
![image](https://user-images.githubusercontent.com/64958726/182329025-7fe52ef2-95d4-437b-a53d-f9bff6854b9b.png)

This occurs quite frequently in our application depending upon the user's screen size and whether or not the navigation panel on the left is open or collapsed.

Our UX team is redesigning some of our screens. I would like to loop them into the conversation, but I do not think they have GitHub accounts.

**Comment by ljemmo** [comment]
@tempertemper please could i get your thoughts on the above screenshot. I believe our guidance would be to suggest wrapping of labelling and getting the fields to the right to bottom-align with the categoria field? ideally though we would just have 1 field per line and stack from recollection of past discussions.

@shavonne-sage Above are my thoughts on what the DS guidance would be but but let's wait to hear back from martin so that we design the most accessible solution. Has your UX designer also considered readonly vs edit views? If the above label wrapping solution that i outlined to martin is not possible, then a stacked edit view might resolve the truncation.

See below for a good example on how stacked editable fields work for Sage for Accountants:
![Screenshot 2022-08-02 at 11 37 58](https://user-images.githubusercontent.com/98600534/182355493-d3c54826-1ebe-4585-aeea-ff4622109a66.png)

Here's the same view on readonly once data has been saved:
![Screenshot 2022-08-02 at 11 38 17](https://user-images.githubusercontent.com/98600534/182355541-6dd44709-9afa-4ee1-8f24-8e6ae69bb482.png)

**Comment by shavonne-sage** [comment]
@ljemmo, I shared this ticket with our UX team and am going to leave this topic in their hands. I will follow the conversation here regardless. Thank you!

**Comment by nicktitchmarsh** [comment]
Do we need to keep this ticket open if there are no recommendations for Carbon at the moment? @shavonne-sage @tempertemper

**Comment by tempertemper** [comment]
@nicktitchmarsh Even when paired with tooltips, the labels are then only available to users with a mouse/pointer. To give a few examples, we're preventing keyboard users, speech recognition users, and touchscreen users getting full information on the details we're asking them to provide.

Hint text may be needed on some form fields, which would break the tidy horizontal alignment; error messages will do the same when (rather than if) they are displayed. Our designs should allow for this flexibility, as well as form labels that wrap onto multiple lines.

This ticket should be closed 👍
