### ISSUE TITLE
ActionPopoverMenuButton - Stay open behind when we open a Dialog

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#4662]
### Current behaviour

When using ActionPopoverMenuButton in a FlatTable with the keyboard, this one stay open when we open a dialog.

### Expected behaviour

ActionPopover would be closed when we open a dialog in front of, like when we use the mouse.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/black-moon-ugf2n?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-25708

### Carbon Version

101.4.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
FE-4703

This is now in progress.

This is caused because when we move the focus, the click event triggers on the button re-opening the menu.

I have been unable to reproduce this in cypress and I have raised https://github.com/cypress-io/cypress/issues/19541 I'll create a unit test for this instead. It would be good to add a cypress test once the cypress issue above is resolved.
