### ISSUE TITLE
[Select] Select list does not close when another component steals focus

### ISSUE THREAD

**Issue by stripeyjumper** [Sage/carbon#4799]
### Current behaviour

- Use keyboard up/down arrows to select an item in a select dropdown
- If selecting an item causes a side-effect, like opening a modal, the focus will move to the modal.
- The select list remains open, on top of the other content, and still responds to keyboard input.

### Expected behaviour

When focus moves away from the select component the select list popover should close.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/hopeful-oskar-45nvn

### Carbon Version

102.16.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
@tempertemper We have a pattern here where a modal is opened when select options are focused. I assume this is not an accessible usage? Would we recommend a different pattern for this case?

**Comment by tempertemper** [comment]
This is a likely failure of [3.2.2 On Input](https://www.w3.org/TR/WCAG21/#on-input) as it’s an unexpected change due to a form input’s value being chosen/changed. The On Input success criterion is open to interpretation, but if there’s any chance that an external audit could come back with a ‘not met’ we should design around it.

I don't have any recommendations for this, but would be happy to jump on a call with a designer to discuss it further.

**Comment by nicktitchmarsh** [comment]
@stripeyjumper, are you ok to arrange a discussion with @tempertemper about best practice regarding this?

**Comment by samtjo** [comment]
@stripeyjumper @tempertemper hi guys, do we have any updates on this? Do we need to raise a ticket to support this?

**Comment by stripeyjumper** [comment]
> @stripeyjumper @tempertemper hi guys, do we have any updates on this? Do we need to raise a ticket to support this?

Hi @samtjo, I've just had a chat with @tempertemper about it.  There isn't a simple fix we can make to work around the issue, so I think it does need a ticket.

There are two ways to fix it that we discussed:
1. Wait until the select list closes before triggering the `onChange` event
   - Avoids doing work while the user is still navigating
   - Might be a breaking change for some apps
2. Watch for loss of focus and close the select list automatically
   - Might be tricky to code
   - Not a breaking change (?)

**Comment by jamime** [comment]
I've raised FE-5016 to investigate this further.

**Comment by samtjo** [comment]
Hi @stripeyjumper - It's possible to fix this behaviour using the `onBlur` prop rather than the `onChange` prop as shown here: https://codesandbox.io/s/vigorous-http-04jewl?file=/src/index.js 

The confirm modal opens onBlur, and only when the selected value has changed. Is this a suitable solution for your issue?

**Comment by nicktitchmarsh** [comment]
This should now be fixed in the latest Carbon https://codesandbox.io/s/sad-bose-rmfshe?file=/src/index.js
