### ISSUE TITLE
[Card] Interactive Card doesn't perform action when enter key pressed

### ISSUE THREAD

**Issue by stripeyjumper** [Sage/carbon#4800]
### Current behaviour

Interactive Card component with the focus does not call its `action` when the "Enter" key is pressed.

### Expected behaviour

The `action` prop should be called when the "Enter" key is pressed

### CodeSandbox or Storybook URL

https://codesandbox.io/s/billowing-night-nzyon

### Carbon Version

102.16.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4916

**Comment by nicktitchmarsh** [comment]
Design System need to clarify how Card should be utilised. The interactive prop emulates the behaviour of a button but does not fulfil keyboard controls. Should we change the interface for this component to allow consumers to specify an onClick action or a href? What are your intentions for the Card component? 

Is there a reason to have the whole card as interactive, rather than having interactive elements inside the card content?

**Comment by ingridzillinger** [comment]
We will notify the front-end development team once the design system is updated.

**Comment by nicktitchmarsh** [comment]
@ljemmo, @ingridzillinger do we know if this got updated at all?

**Comment by ljemmo** [comment]
@nicktitchmarsh We have no specs created other than default and hover. However, when a card is in focus and enter is hit, i'd expect the card link to open. e.g a bank card is in focus.
