### ISSUE TITLE
Typography is not applied to Link component when it contains onClick

### ISSUE THREAD

**Issue by YariMVSage** [Sage/carbon#4828]
### Current behaviour

Typography is applied to Link components that opens external links but when they have an onClick prop, Typography is not applied.

### Expected behaviour

I would like to be able to set the font size of all kind of Link components

### CodeSandbox or Storybook URL

https://codesandbox.io/s/gracious-christian-od19q?file=/src/index.js

### Carbon Version

102.2.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
There is a possible workaround for this issue, a link is actually rendered as a button when it is given an onClick function and no href is applied. You could add a self targeting href which would force the typography to be applied correctly. I believe we are seeing this issue due to overriding button styling. 

I have raised an issue FE-4947 to discuss this within the team

**Comment by nicktitchmarsh** [comment]
Hi @YariMVSage, you can compose the typography into the link itself. Please see the attached sandbox https://codesandbox.io/s/awesome-wilson-mpn6j2
