### ISSUE TITLE
ISO date format not supported

### ISSUE THREAD

**Issue by ggeis** [Sage/carbon#4966]
### Current behaviour

When setting a **zh-CN** localization, the date input reformats to the day-month-year format instead of ISO 8601.

### Expected behaviour

When setting a **zh-CN** localization, the date input reformats to the right format: ISO 8601.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/ancient-wave-0d3m3t

### JIRA Ticket (Sage Only)

XT-21014

### Suggested Solution

I think new hardcoded language tags (at least `zh-CN`, but maybe `pl`) can be added to the *src/components/date/_\_internal__/date-formats/index.js* `getFormatDate` function. Also, some ISO input formats as you have for EU_FORMATS and NA_FORMATS.

### Carbon Version

104.27.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5035

**Comment by blaky** [comment]
Actually, it turns out to be it's more than that: some date formats are hard-coded in a date utility and carbon does not use the provided date formats from the date provider.

https://github.com/Sage/carbon/blob/b9f3a5f6ca44264bb6a1b0e7b7b5106f1b4ce51d/src/components/date/__internal__/date-formats/index.js
