### ISSUE TITLE
Tooltip message sticks on the screen without disappearing after choosing controlled Toggle tooltip

### ISSUE THREAD

**Issue by ZhuoyuJin** [Sage/carbon#5016]
### Current behaviour

Repro step:
1. Go to Storybook tooltip component, controlled story. 
2. Click on "Toggle tooltip"
3. A tooltip message should show on the screen, then switch to Docs or switch to other stories
4. The tooltip message sticks on the left corner of the screen without disappearing 

https://user-images.githubusercontent.com/72838192/161561514-8ce6c8a0-9603-432d-b910-2633e9cfdc85.mp4

### Expected behaviour

The tooltip message should disappear when switch to Docs or to other stories

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/tooltip--controlled

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
Thanks for raising - I've investigated this, and unfortunately it's a Storybook bug (or intentional "feature") that is out of our control. 

When you switch from Canvas to Docs view on Storybook, it doesn't actually unmount the contents of the story open in Canvas, it just sets `hidden="true"` on the root element. The docs page has a different root with an id of `docs-root`. 

![image](https://user-images.githubusercontent.com/14963680/162450682-8ad7fe04-39cd-4e65-86b5-63a5f0447496.png)

So as far as the tooltip is concerned here, the element it's attached to hasn't unmounted and it correctly isn't destroyed. So there's nothing wrong with our Tooltip component and I'll close this issue 👍🏻
