### ISSUE TITLE
No sound after moving cursor on select filterable with action button

### ISSUE THREAD

**Issue by AgnieszkaRadecka** [Sage/carbon#5168]
### Current behaviour

1. Go to https://carbon.sage.com/?path=/story/select-filterable--with-action-button
2. Turn on NVDA tool
3. Move the cursor to select

There is no information about this select

### Expected behaviour

NVDA should tell me about this field

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/select-filterable--with-action-button

### JIRA Ticket (Sage Only)

SBS-32304

### Carbon Version

106.6.5

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5182

**Comment by robinzigmond** [comment]
@AgnieszkaRadecka when I test the link with NVDA (via Browserstack) and focus the select, whether by clicking or by using the tab key, I hear it described as "color combobox collapsed has autocomplete editable please select" - which while a bit of a mouthful, does contain all the relevant information. Can you confirm whether you still see an issue with this component? (Perhaps it has been fixed independently since May?)

**Comment by grabkowski** [comment]
I think that it was probably fixed in this PR:
https://github.com/Sage/carbon/pull/5865
