### ISSUE TITLE
Too big contrast for days of the week in datepicker

### ISSUE THREAD

**Issue by AgnieszkaRadecka** [Sage/carbon#5173]
### Current behaviour

1. Open https://carbon.sage.com/?path=/story/date-range--default-story
2. Click on datepicker icon
3. Inspect 'MON'

There is too big a contrast 3.96. It doesn't qualify for AA level 
![image](https://user-images.githubusercontent.com/104970395/170196981-5f20dc68-ea52-4045-a8fd-d40ee10e3f12.png)

### Expected behaviour

There should be 2.65 contrast

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/date-range--default-story

### JIRA Ticket (Sage Only)

SBS-32304

### Carbon Version

106.6.6

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
Hi @AgnieszkaRadecka
Thanks for letting us know about this. I think the issue is that the contrast ratio [should be at least 4.5:1 to meet AA standards](https://www.w3.org/TR/WCAG21/#contrast-minimum). So we will need to make the text darker to meet this success criterion. @harpalsingh would you agree with this?

**Comment by AgnieszkaRadecka** [comment]
yes

**Comment by Parsium** [comment]
FE-5199
