### ISSUE TITLE
Impossible to change height of Filterable Select

### ISSUE THREAD

**Issue by WojciechMichalowski** [Sage/carbon#5257]
### Desired behaviour

https://carbon.sage.com/?path=/docs/select-filterable--default-story#new-designs-validation
<img width="1165" alt="Zrzut ekranu 2022-06-23 o 13 52 55" src="https://user-images.githubusercontent.com/102224763/175292646-764ca426-4025-4c98-ab0b-fcd21b3c0374.png">

### Current behaviour

height is hardcoded (dropdown)

### Suggested Solution

add prop to change height

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
@harpalsingh Do we want to be allow users to control the height of the dropdown of Select?

**Comment by nicktitchmarsh** [comment]
@ljemmo Could you advise on this please?

**Comment by ljemmo** [comment]
@nicktitchmarsh  and @DipperTheDan do we know why this override was requested? I believe the current hardcoded height is by design. I think if there's enough of a strong rationale, then we could certainly consider adding this in.

**Comment by WojciechMichalowski** [comment]
overside is bcs of figma designs

**Comment by rawlmp** [comment]
Jira Ticket issue:
SBS-35835

**Comment by lukepricesage** [comment]
Hi All, 
For context, I'd just like to provide some justification as to why this override has been requested and the design problem we are facing due to the limitation...

Our 'transaction processing UI' is built with the primary purpose of enhancing productivity for our users processing their bank feed transactions. To remain compliant, assigning one category per transaction is the primary function - this is the most frequent action a user will perform in MTD ITSA Tier 1.  

In the screen grab below you will note that we have included a supporting message description for each transaction category (in this instance 'Wages, and staff costs') which can be toggled on or off by preference and has tested well. However, this does mean that at any one time a user can only view one transaction category in the drop-down list even though on a larger monitor we have the real estate to reduce unnecessary scrolling. 

<img width="1455" alt="filterable-select-height-issue" src="https://user-images.githubusercontent.com/87415539/184680827-a097c147-3b3a-49ff-b5b4-b4616c7529f7.png">
