### ISSUE TITLE
Filter : forwardRef doesn't work in separate component

### ISSUE THREAD

**Issue by hagad** [Sage/carbon#5381]
### Current behaviour

When we open a filter (PopoverContainer)->  The component is opened at the bottom of the page.
The issue is because if  Badge Component is defined in another component ->   forwardRef prop is always 
It works if we define the badge in the same file as PopoverContainer.

### Expected behaviour

The component should be opened correctly.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/friendly-cray-9zegtx?file=/src/FilterButton.js

### Carbon Version

v110.0.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5312

**Comment by mkrds** [comment]
It looks like it actually works ok. I've fixed it in your codesandbox https://codesandbox.io/s/relaxed-boyd-evmof5?file=/src/FilterButton.js:498-508

In your version you pass `ref` to a `FilterButton` component even though it's not using the `React.forwardRef`. Because of that `ref` is not passed to the `Button` component and `PopoverContainer` does not have an element which it can position itself relatively to.

https://reactjs.org/docs/forwarding-refs.html
