### ISSUE TITLE
Golden focus outline in Drawer with tab controls

### ISSUE THREAD

**Issue by KonradWroblewski** [Sage/carbon#5598]
### Desired behaviour

The User should know where focus is and it should be presented just like in other components of the application - that is, golden outline.
![image](https://user-images.githubusercontent.com/112560351/200291813-f830dddd-e6a0-4996-9b63-0ff210a14498.png)

### Current behaviour

 Tabs component has a focus outline by default, but if we combine it with Drawer component as sidbar, then golden focus outline does not appear.
 
![image](https://user-images.githubusercontent.com/112560351/200291696-01a3f79e-3154-4c7c-a569-2fb86310dc82.png)

### Suggested Solution

This should look like  in the Tabs component by default.

https://carbon.sage.com/?path=/docs/tabs--default-story

### Anything else we should know?

SAGE JIRA Ticket - SBS-33896

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
@ljemmo would you mind looking into this please? Tagging @harpalsingh as I believe he did the original designs

**Comment by ljemmo** [comment]
@KonradWroblewski  - agreed that focus states need supporting here. If we are following the same approach to the tab component, we should tab onto the first tab item, then up and down control where the focus jumps to.

However, i thought that we were moving away from using arrow keys in situations like this  in favour of just continuously pressing tab to jump through each button. @tempertemper Can you confirm? 

@edleeks87  if yes to the question for martin, then we should probably consider fixing all tabs (not just drawer tabs) in one PR.

**Comment by tempertemper** [comment]
Tabs should behave like a button group, so:

- The tab key takes the keyboard user on the the group, focusing the first item
- The user moves through the options in the group using the arrow keys
- Another press of the tab key takes the user off the button group (tabs) and onto the next control in the interface

That doesn't change the need for a focus state, so we should still be adding the standard golden focus outline 👍 

The continuous tab key pressing that you're describing, @ljemmo, would be for navigation rather than tabs. With navigation, the items are links, not buttons, so the user's navigation expectation would be different. I've been speaking to @harpalsingh about this, and he's thinking about how we might better visually distinguish vertical tabs and sidebar navigation.

**Comment by nicktitchmarsh** [comment]
FE-5545 has been raised to address this
