### ISSUE TITLE
Add a new input field for passwords

### ISSUE THREAD

**Issue by Dlyx24** [Sage/carbon#5614]
### Desired behaviour

Have an input component that can be used as a type="password" input.

### Current behaviour

There is currently no way using Sage Carbon Library to create a input of type="password".
Using Carbon Library one can achieve this by using the TextInput component that as the "type" prop to be passed.

The best I can achieve using Sage Carbon is by using the TextBox component which lets me costumize my input as I want but doesn't allow to pass any prop of "type" to the input.

However, if you force the type="password" prop to be passed on the TextBox component it will have effect when the input is rendered in the browser. Typescript is of course not happy with me passing the type="password" prop when it doesn't exist in the component.

### Suggested Solution

Create a specific password component that allows functionallity like icons and clicking the icons to change the type from password to text so the user can see what they have inputed. 

OR

Add the type prop to the Textbox component since it already seems to accept it internally but it is not on the accepted props.

### Anything else we should know?

Question was asked on Sage Slack channels and it was answered by James Parslow.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @ljemmo, currently in Carbon we allow consumers to specify the type of input that `Textbox` will use, by default it is text, but they can specify other input types such as passwords, email addresses or numbers (see this [full list of accepted types ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types) for reference, essentially we are passing `Textbox`'s `type` prop to the `type` attribute of the underlying `<input>` html element).

This raised issue is due to a technicality after migrating `Textbox`'s code to TypeScript, however it raises a bigger design question if we should be allowing consumers to freely specify what type of input `Textbox` accepts. This could be problematic as consumers could specify types such as dates, search fields, checkboxes, etc. which is not what `Textbox` is designed for.

I can see two ways of addressing this:
1. We limit the types of input `Textbox` can accept to text-based ones such as text, passwords, emails, etc. Ideally we should have this stated in the Design System as well.
2. We create a dedicated component for inputting passwords - similar to how we have specific variants of DS's Text Input component, such as `NumeralDate` and `Search`, for accepting specific input types.

What do you think?

**Comment by Dlyx24** [comment]
Any news regarding this ?

**Comment by Parsium** [comment]
> Hi @ljemmo, currently in Carbon we allow consumers to specify the type of input that `Textbox` will use, by default it is text, but they can specify other input types such as passwords, email addresses or numbers (technically speaking we are passing `Textbox`'s `type` prop to the underlying `<input>` html element, see this [full list of types ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types) that `<input>` accepts for reference).
> 
> This raised issue is due to a technicality after migrating `Textbox`'s code to TypeScript, however it raises a bigger design question if we should be allowing consumers to freely specify what type of input `Textbox` accepts. This could be problematic as consumers could specify types such as dates, search fields, checkboxes, etc. which is not what `Textbox` is designed for.
> 
> I can see two ways of addressing this:
> 
> 1. We limit the types of input `Textbox` can accept to text-based ones such as text, passwords, emails, etc. Ideally we should have this stated in the Design System as well.
> 2. We create a dedicated component for inputting passwords - similar to how we have specific variants of DS's Text Input component, such as `NumeralDate` and `Search`, for accepting specific input types.
> 
> What do you think?

Hi @clairedenning @harpalsingh, what do you think about the two suggested solutions above? 

We should be able to proceed easily with the second solution without further action from the DS team, but with the first one it would be good to have Design System state for the Text Input component that only alphanumeric text is accepted as input.

**Comment by Parsium** [comment]
Hi @clairedenning @harpalsingh, reviewing my previous comment we should actually be able to proceed with this without further action from Design System given this is more of a technical issue rather than a design issue. 

However, it may be a good idea to include some design variants for passwords for the Text Input component for completeness, given password characters should be redacted when entered. What do you think?

**Comment by Parsium** [comment]
FE-5614

**Comment by clairedenning** [comment]
@Parsium I think that's a good idea to include it in ZH. Can you send me a screengrab of how it would look please?

**Comment by Parsium** [comment]
> @Parsium I think that's a good idea to include it in ZH. Can you send me a screengrab of how it would look please?

@clairedenning so this is what a Text Input component that collects passwords would like. The input is text as normal but with the characters being redacted by rendering them as dots: 

<img width="567" alt="Screenshot 2023-01-11 at 13 42 51" src="https://user-images.githubusercontent.com/18368713/211821474-793339be-6e13-4535-b818-08bb203d37b2.png">

**Comment by clairedenning** [comment]
@ingridzillinger  can we add this to our backlog?

**Comment by ingridzillinger** [comment]
Added this ticket: DSY-2183 (Design System backlog)
