### ISSUE TITLE
Decimal field with precision not working as expected

### ISSUE THREAD

**Issue by SAHesse** [Sage/carbon#5625]
### Current behaviour

A given precision of 4 formats a given or typed value "0.18" to "0.1800". A given or typed value "0.18127" is formatted to "0.18127".

### Expected behaviour

 A given or typed value "0.18127" should be formatted to "0.1813", when a precision of 4 is given

### CodeSandbox or Storybook URL

https://codesandbox.io/s/dry-bush-0qn2hx?file=/src/DecimalField.tsx

### Carbon Version

110.0.3

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS, Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
This issue has been closed after some accessibility and user experience concerns were raised due to the nature of the fix. It is poor practice to modify the user input automatically, instead validation should be used to inform users of any formatting mistakes, so they can make an attempt to rectify them. We believe how the component works currently is fit for purpose. Please feel free to raise another issue if you have any other concerns, requests, or have discovered any issues or bugs. Thanks.
