### ISSUE TITLE
Error when disabling a component that has a validation error

### ISSUE THREAD

**Issue by vanchetty** [Sage/carbon#5627]
### Current behaviour

We have validations on some of the components that we are using, and we sometimes disable/enable these components depending on the user selection.
We now get an error when disabling a component that has a validation error.
This was not a problem for us in the previous versions of Carbon, however we are now getting errors after upgrading Carbon to version 111.8.2.

### Expected behaviour

We need to be able to disable components with validation errors.  When these components are enabled based on a user selection, the validation errors still need to appears on those previously disabled components when re-enabled.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/laughing-dirac-ombq0d?file=/src/index.js

### JIRA Ticket (Sage Only)

SPAR-7389

### Carbon Version

111.8.2

### Design Tokens Version

2.48.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
Hi @vanchetty , the problem is that disabled fields are not accessible, and therefore the error messages are not accessible in the current designs. With Sage's commitment to meeting WCAG 2.1 we should be trying to make all patterns accessible for all users, including those using Screen Reader technology. 

For inputs that have the option, you can use `readOnly` props to make the field uneditable while still focusable. If there are any components that do not have access to `readOnly` which you need please raise a new issue.
