### ISSUE TITLE
Tab - Add warning/error icon without text

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#5668]
### Desired behaviour

We would like to only display warning/error/info icon without necessary a text to display when hover icon.

### Current behaviour

Currently, we can only add warning/error/info icon if string is passed to the property, and having a text displayed when hover the icon.
We could manage that by siblings property but the icon is not center aligned with the text. (as we could have with warningMessage property). 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
@ljemmo whats your opinion on this from a DS standpoint? Personally I feel a boolean validation in this use case would not be good for user experience/accessibility hence it not being included originally. What do you think?

**Comment by Chris3y** [comment]
@maduv 

While it's not exactly what you're asking for, would this pending enhancement be worth considering anyway? Rather than blank text, it summaries any validation messages?

https://github.com/Sage/carbon/issues/5618

**Comment by ljemmo** [comment]
So we would always want to include text next to fields when they're erroring out. I'm not sure why this would be needed. Can you get your designer to liaise with me @maduv ?

**Comment by Parsium** [comment]
Hi @ljemmo @maduv 👋🏼 Were we able to reach a verdict with this one?

**Comment by ChrisBPetty** [comment]
The original driver behind this was for large tabbed forms where the Save button may be pressed while the user cannot see the part of the form with the errors occurring. Now we have moved to having proper inline validation messages on individual text inputs and are moving to having an error summary, the tooltip on the icon seems a bit redundant as we can't currently give a meaningful message. Chris's pending enhancement might improve the situation here and if something like that feels more elegant @ljemmo, I'm happy to go with that.

**Comment by Parsium** [comment]
Thanks for the context @ChrisBPetty 👍🏼 It sounds like this problem is a result of a clash between the old tooltip design and newer validation message redesign.

We have made a release back in December that allows developers to pass summarised validation messages to tab icon tooltips (linked to the issue @Chris3y raised above). This has been part of Carbon since version `111.19.0` and we have some technical documentation related to it in [our docs](https://carbon.sage.com/?path=/docs/tabs--default-story#with-string-validations-summarised). So hopefully this should help address this issue for you and @maduv?
