### ISSUE TITLE
Pager inside a form triggers a click on the Previous page link

### ISSUE THREAD

**Issue by andreiamar** [Sage/carbon#5675]
### Current behaviour

When having the Pager component used inside a form, after typing the current page number in the input field and pressing Enter it appears that the onPrevious callback function is called and the current page input value is decreased by one. This does not happen for a 2nd Pager component inside the form.

### Expected behaviour

The current page value should be the value that the user typed, if it is a valid page number.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/brave-sutherland-ddijv9

### JIRA Ticket (Sage Only)

SBS-47252

### Carbon Version

111.8.3

### Design Tokens Version

2.45

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
@ljemmo thoughts on this, a few issues have been raised regarding using a pager inside a form. Is a pager inside a form something we should support?

**Comment by ljemmo** [comment]
@tomdavies73 i'm unsure why pagination would ever be needed in a form. Can i see some design examples so i can comment further? @andreiamar

**Comment by Parsium** [comment]
Hi @andreiamar, were you able to share the designs you were given with Luke?

**Comment by andreiamar** [comment]
<img width="436" alt="image" src="https://user-images.githubusercontent.com/112492571/211594004-bab9124c-a878-4c8e-b2af-d4df9011d9d3.png">

@ljemmo @Parsium Here's the screenshot. Our entire page content is placed inside a Form.

**Comment by Parsium** [comment]
Thanks for this @andreiamar 👍🏼 

@clairedenning @ingridzillinger currently in Carbon the pattern of having `Pager`s inside of a `Form` is  something we support. This issue looks like a clear bug to me which we can easily look into, however, given Luke's raised concerns regarding this pattern, may I ask your thoughts on this pattern and the above use case Andrei has shared?

**Comment by clairedenning** [comment]
@Parsium have you considered using a Step flow? https://zeroheight.com/2ccf2b601/v/30605/p/405a47-step-flow/b/83830f 
![image](https://user-images.githubusercontent.com/49988488/212028144-65f1ce99-8d45-4f59-ad21-84e39b63aca1.png)

Best practices include:

- Include previous and next buttons and label them consistently.
- Allow the user to return to a previous step to review their data submission.

**Comment by Parsium** [comment]
Thanks @clairedenning 👍🏼 

After speaking with @andreiamar about the design, I think the Form with pagination pattern has been used here since they need to display a possibly long list of search results where the user can only select one, as opposed to using this pattern to create a linear journey of steps (the business search page appears to be a step in broader linear journey, not the results in the form themselves). 

This has been done to improve readability (compared to displaying the results in a possibly long dropdown list) and to account for the fact that most users will likely select a business from the first set of search results. I've had a look at some of other design systems and it appears [UKGov](https://design-system.service.gov.uk/components/pagination/) justifies the use of pagination for similar reasons.

This sounds like an appropriate use case to me unless you think otherwise?

**Comment by Parsium** [comment]
Hi @clairedenning @ljemmo, do you guys have any thoughts regarding the message above?

**Comment by Parsium** [comment]
Thanks @ljemmo 👍🏼 In that case we will raise a ticket for this to address the bug

**Comment by Parsium** [comment]
FE-5706
