### ISSUE TITLE
Textbox characters count - Accessibility

### ISSUE THREAD

**Issue by victoriadeanton** [Sage/carbon#5717]
### Desired behaviour

In Textbox or Textarea with the characterLimit functionality
![Screenshot 2023-01-03 at 12 18 58](https://user-images.githubusercontent.com/85164705/210348265-576f55e3-2a4e-483a-b0b8-ccc3d53e99ef.png)
the VoiceOver reads 7/10, it would be desirable to read 3 remaining characters

### Current behaviour

the VoiceOver reads 7/10

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @tempertemper 👋🏼 Using a screen reader on `Textbox` reads out the character counter as "7 slash 10", which we agreed isn't the most descriptive. Do you agree with the solution that has been proposed here? Or should we amend it to read something such as "7 characters out 10"?

**Comment by tempertemper** [comment]
I'd defer to the [GOV.UK character count component here](https://design-system.service.gov.uk/components/character-count/) and use the same content visually (the label) and behind the scenes (the accessible name). "7/10" might not make sense to all users visually either, without some extra thought, and could be mistaken for words rather than characters. The GOV.UK component says "You have 200 characters remaining" after the text box.

Me, I'd recommend two things:

- Use a sentence rather than numbers and a slash (3 characters remaining)
- Don't make hint text optional: if there's a character limit, the user should be told in advance of the input

I'll run this by Andy Varley on the DS team when I next speak to him.

**Comment by v99rly** [comment]
I agree with Martin. For me there should be hint text before the input advising there is a character count and then at the bottom a sentence that read something like XX characters remaining. 

Ill create a ticket in the Design system backlog to update the guidance on character count component.

**Comment by nicktitchmarsh** [comment]
@v99rly can you comment with the DSY ticket number so I can link it to a task on our side?

**Comment by v99rly** [comment]
Looks as though the original ticket was closed so I've created a new one - DSY-2390 - https://jira.sage.com/browse/DSY-2390

**Comment by nicktitchmarsh** [comment]
FE-5679

**Comment by nicktitchmarsh** [comment]
FYI I think we should implement your recommendations that are stated here. So we will go ahead with this change.
