### ISSUE TITLE
Being able to display no action information in MenuItem component

### ISSUE THREAD

**Issue by YariMVSage** [Sage/carbon#5718]
### Desired behaviour

This request comes from an "issue" we have detected since a carbon update. In the past we were able to display no-action information in the MenuItem component. Since this update, padding has disappeared from elements that has not got any action to do.

### Current behaviour

Currently information is displayed with no padding and also the cursor appears when hovering a MenuItem that has got no actions

### Suggested Solution

We use the MenuItem to display information. In our application the user can log out, and we are displaying in the same menu the last access date, we would like to being able to display this kind of information with the padding like in the past and if possible, without a cursor as no actions are associated to this element. Or maybe we will like to have a new component to do that available.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/goofy-maria-ohbtpn?file=/src/index.js 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @YariMVSage, thanks for sharing the additional context regarding this issue. For what you are trying to achieve, I'm not sure if placing this information about previous login date inside a `MenuItem` is the best way to go about it - since the user isn't navigating to a new link nor achieving a particular action.

I would perhaps get in touch with Design System regarding how to achieve the functionality you are looking for as they may suggest a better alternative.

**Comment by YariMVSage** [comment]
Hello @edleeks87 @Parsium after some conversations with a member of UX team we have agreed to use another design without MenuItem component in order to display this kind of information. Thanks
