### ISSUE TITLE
16px Margin between Accordion Icon and Heading

### ISSUE THREAD

**Issue by Isabelle-whi** [Sage/carbon#5909]
### Desired behaviour

Smaller Gap between a  left Icon on of an accordion heading and the heading text.

### Current behaviour

16px margin on right side of Icon. Puts a large gap between Icon and the text to the right of it.

### Suggested Solution

Smaller margin on the right side of icon or a way of setting the margin using the headerSpacing prop.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/elegant-euclid-jn12m1?file=/src/App.js

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nineteen88** [comment]
Hi @ljemmo - what are your thoughts on this? Should we allow the margin right to be updated by the user? Currently it's set to 16px.

**Comment by ljemmo** [comment]
@nineteen88 so it looks like isabelle is trying to manually code our secondary style accordion treatment with dropdown carats instead of chevrons. I think rather than letting her update the margin-right in the heading and create a bespoke accordion - what probably makes more sense is introducing a new prop to change the accordion style from primary to secondary. Are you ok to create a ticket for this on your board?

**Spec** 
https://www.figma.com/file/Tau6qv5iyr8wthWNqYktej/DS-Official-Components?node-id=27182%3A261578&t=vAc22AJnJESqQAVz-4

**A/C**
* add a prop to enabl the secondary accordion treatment
* introduce the left-border on secondary treatment when open
* introduce the accordion up and down chevrons following the spacial markup and tokens in the spec
* make sure the action button left-aligns with the body copy inside the component
* Add hover state for secondary accordion (text and chevron go darker green) {colors.action.major.600}

**Comment by edleeks87** [comment]
FE-5728 has been raised to cover the enhancements proposed by @ljemmo. I'm closing this issue for now, please re-open if you think it's not going to address your problem
