### ISSUE TITLE
Installation fails due to GitHub rate limit issues

### ISSUE THREAD

**Issue by blaky** [Sage/carbon#5917]
### Current behaviour

Occasionally, when we build a project using `carbon-react` it fails with the following error on installation:

```
RequestError [HttpError]: API rate limit exceeded for 51.103.107.49. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
#18 78.84     at /xtrem/app/node_modules/@octokit/core/node_modules/@octokit/request/dist-node/index.js:86:21
#18 78.84     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
#18 78.84     at async getOpenRfcs (/xtrem/app/node_modules/carbon-react/scripts/check_rfcs/check_rfcs.js:20:20)
#18 78.84     at async checkRfcs (/xtrem/app/node_modules/carbon-react/scripts/check_rfcs/check_rfcs.js:42:20) {
#18 78.84   status: 403,
#18 78.84   response: {
#18 78.84     url: '[https://api.github.com/repos/sage/carbon/pulls'](https://api.github.com/repos/sage/carbon/pulls%27),
#18 78.84     status: 403,
#18 78.84     headers: {
```

This is very inconvenient if it happens in our nightly builds (it happened twice in the last week), because then our environments are not updated next day and our nightly integration tests are not executed.

### Expected behaviour

The installation should not stop even if this call fails, given this call seems to be for information purposes only.

### CodeSandbox or Storybook URL

N/A

### Suggested Solution

Catch any HTTP error that happens during the NPM postinstall scripts so they don't block the installation.
OR
Skip the call when a specific env var is defined. 

### Carbon Version

114.17.1

### What browsers are you seeing the problem on?

Other

### What Operating System are you seeing the problem on?

Other

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by przemyslawzalewski** [comment]
The issue seems to come from some post-install script and as a workaround please consider turning them off during installation with `--ignore-scripts` flag - `npm ci --ignore-scripts` (or in the last resort, `npm install --ignore-scripts`). This will also make your install more secure by avoiding random post-install scripts firing and possibly other supply chain attacks 🛡️ 

For the Carbon team, it would be expected to remove the post-install hook as it seems to be an entirely internal thing and never ship it to consumers: https://github.com/Sage/carbon/blob/master/package.json#L23 (`"postinstall": "node ./scripts/check_rfcs/check_rfcs.js"`).

**Comment by edleeks87** [comment]
Thanks for raising this @blaky and for your comments @przemyslawzalewski. It's intended for consuming projects to notify of any open RFCs. We used to see this issue intermittently but haven't for a while now so it may caused by differences in CI environments. I don't think this script offers much value personally so I'll see if I can get some traction to get it removed

**Comment by blaky** [comment]
> The issue seems to come from some post-install script and as a workaround please consider turning them off during installation with `--ignore-scripts` flag - `npm ci --ignore-scripts` (or in the last resort, `npm install --ignore-scripts`). This will also make your install more secure by avoiding random post-install scripts firing and possibly other supply chain attacks 🛡️
> 
> For the Carbon team, it would be expected to remove the post-install hook as it seems to be an entirely internal thing and never ship it to consumers: https://github.com/Sage/carbon/blob/master/package.json#L23 (`"postinstall": "node ./scripts/check_rfcs/check_rfcs.js"`).

Hi @przemyslawzalewski 

We did consider it but we need the postinstall script for some other dependencies, so this would not be a definitive solution. We are aware that this is a risk for supply chain attacks, that's why we use a package-lock file and an NPM proxy to mitigate the risk.

**Comment by przemyslawzalewski** [comment]
Thanks for your input @edleeks87 and @blaky. I think we have then concluded that the only definitive way is to either remove this post-install script from Carbon (preferred) and/or make it fail-safe (try/catch no-op) ✅

**Comment by nineteen88** [comment]
FE-5720

**Comment by blaky** [comment]
Thanks for the work on this!
