### ISSUE TITLE
`Dialog`,`Sidebar`,`DialogFullScreen` and `Confirm` components to implement dialog role and aria-modal

### ISSUE THREAD

**Issue by JinCoreana** [Sage/carbon#5920]
### Current behaviour

**This is an extended issue of https://github.com/Sage/carbon/issues/5631** 

When `Dialog`,`Sidebar`,`DialogFullScreen` or `Confirm` is open,  Windows voice-recognition captures all elements in the DOM, including those located under the modal. 

The screenshots below were taken from the attached sandbox example.

When `Sidebar` is open
![example1](https://user-images.githubusercontent.com/90848080/225070387-1d45226a-8439-4365-ae64-5b27f1acba37.png)

When `Dialog` is open
![example2](https://user-images.githubusercontent.com/90848080/225070767-5fa7cdec-be32-4cf8-a740-b4f518442ef1.png)

When `DialogFullScreen` is open
![example3](https://user-images.githubusercontent.com/90848080/225070786-7ad6b6ac-81c9-4fe4-869e-83f34e740fc0.png)

When `Confirm` is open
![example4](https://user-images.githubusercontent.com/90848080/225070859-c83ac094-2864-478f-bf0f-7ac0d4712a71.png)

### Expected behaviour

Opening a modal programatically should hide the targetable elements below the modal.

### CodeSandbox or Storybook URL

https://1161ng.csb.app/

### JIRA Ticket (Sage Only)

SBS-54546

### Suggested Solution

The same solution suggested in https://github.com/Sage/carbon/issues/5631

### Carbon Version

114.18.1

### Design Tokens Version

2.45.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

**This is an extended issue of https://github.com/Sage/carbon/issues/5631** 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5726

**Comment by robinzigmond** [comment]
Having looked into this for a while I'm not sure there's any "fix" within Carbon that is worth doing for this.

This seems to be a fundamental issue with Windows Speech Recognition - and indeed with speech recognition more generally, as I can reproduce similar issues with Voice Control on Mac.

Testing with the Aria Practices example of an accessible Modal component https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/ I observe exactly the same behaviour as in this bug - when the modal is open, "show numbers" unfortunately still puts numbers beside otherwise-interactive elements which are not in the modal. Note that both this example and the Carbon dialog (etc) use `aria-modal="true"` on the dialog, so it's not particularly surprising that they behave the same way.

While not ideal, this doesn't seem to be a huge problem as, when attempting to interact with an element not in the modal via speech recognition, while the command is recognised nothing actually happens. (You can test this on the Carbon documentation page, eg by trying to activate one of the "show code" buttons.) So Speech Recognition does seem to "know" that the elements aren't expected to be interactive, even though it still highlights them when "show numbers" is said.

I have tried testing a fix which adds `aria-hidden="true"` to all elements outside the modal - but this doesn't seem to improve things very much or at all. In particular, numbers are still attached to "background" elements when saying "show numbers" with the modal open.

@JinCoreana what are your thoughts on this? While it would be nice to put in a fix, it doesn't look like one is really possible - and as it only affects "show numbers" which is only supposed to be a workaround anyway, I hope this isn't considered too serious. I'm going to bring @tempertemper into this conversation too for the expert opinion!

**Comment by JinCoreana** [comment]
> Having looked into this for a while I'm not sure there's any "fix" within Carbon that is worth doing for this.
> 
> This seems to be a fundamental issue with Windows Speech Recognition - and indeed with speech recognition more generally, as I can reproduce similar issues with Voice Control on Mac.
> 
> Testing with the Aria Practices example of an accessible Modal component https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/ I observe exactly the same behaviour as in this bug - when the modal is open, "show numbers" unfortunately still puts numbers beside otherwise-interactive elements which are not in the modal. Note that both this example and the Carbon dialog (etc) use `aria-modal="true"` on the dialog, so it's not particularly surprising that they behave the same way.
> 
> While not ideal, this doesn't seem to be a huge problem as, when attempting to interact with an element not in the modal via speech recognition, while the command is recognised nothing actually happens. (You can test this on the Carbon documentation page, eg by trying to activate one of the "show code" buttons.) So Speech Recognition does seem to "know" that the elements aren't expected to be interactive, even though it still highlights them when "show numbers" is said.
> 
> I have tried testing a fix which adds `aria-hidden="true"` to all elements outside the modal - but this doesn't seem to improve things very much or at all. In particular, numbers are still attached to "background" elements when saying "show numbers" with the modal open.
> 
> @JinCoreana what are your thoughts on this? While it would be nice to put in a fix, it doesn't look like one is really possible - and as it only affects "show numbers" which is only supposed to be a workaround anyway, I hope this isn't considered too serious. I'm going to bring @tempertemper into this conversation too for the expert opinion!

Hi @robinzigmond, Thanks for looking into this! I have raised this issue because our QA team consistently reports this matter with all modals as bugs to be fixed. I am aware that this issue is directly related to the natural behaviour of Windows voice recognition. So I attended accessibility surgery before posting this issue to seek expert opinions. @tempertemper has confirmed that this should indeed be considered a bug, as Windows users are unable to effectively access elements through voice recognition. To see what's happens when there are over 1000 elements in DOM, please refer to SBS-27936 and SBS-54546. Simply the browser gets frozen in such situations.  I have checked from this sandbox example(https://codesandbox.io/s/bb47m2?file=/src/DialogModal.js) that `aria-hidden` attribute works with Window voice recognition so maybe we could improve the current behaviour a little bit at leaset?I will await further guidance from @tempertemper regarding this matter.

**Comment by robinzigmond** [comment]
thanks for the reply @JinCoreana !

However, I am not observing the same as you. I tried your codesandbox, and while I can confirm it behaves as intended with Voice Control on Mac, it does not appear to do so with Windows Speech Recognition, as you can see in the screenshot below:

<img width="1780" alt="image" src="https://github.com/Sage/carbon/assets/25186376/a2f5350f-0dfb-416a-ad80-fcd982a86926">

(Ignore the fact you can also see Mac Voice Control on the screen - that was asleep at the time, this is testing on a Windows VM on my Mac 😀 ).

And this matches what I saw myself when testing trying to add `aria-hidden` myself to the non-modal elements, in a way that's somewhat similar to what you're doing in the sandbox.

I'm curious why we are observing different things...

**Comment by JinCoreana** [comment]
Hello, @robinzigmond 
Sorry for the delay in my response. I missed your second comment🙏🏻. Here's what I can see from my Windows PC with [this example](https://codesandbox.io/s/bb47m2?file=/src/DialogModal.js)
I really have no idea why this behaves differently in your PC. 🤷🏻‍♀️

without `aria-hidden`
![Screenshot 2023-06-05 at 09 52 19](https://github.com/Sage/carbon/assets/90848080/7adcec09-aac5-4c09-8f30-cc40101ba255)

with `aria-hidden`
![Screenshot 2023-06-05 at 09 52 29](https://github.com/Sage/carbon/assets/90848080/9f8dfd21-c6a2-4319-aa50-4b42bd5c31a0)

**Comment by robinzigmond** [comment]
thanks for the reply! I'm also not sure what's happening - but I can test again, as well as ask others on the team what they see when testing your sandbox on a Windows VM.

**Comment by robinzigmond** [comment]
hi again @JinCoreana ,

I've since retested this on a Windows VM, as has @sianford from our QA team, and we observe the same - that your sandbox does not appear to fix the issue with modals and Windows Speech Recognition.

May I ask precisely which version of Windows, and which browser and version, you are using when observing this as fixed?  With this information, hopefully we will be able to observe the same thing as you are. Thanks!

**Comment by JinCoreana** [comment]
Good morning, @robinzigmond ! Sorry for the delay in response 🙏🏻
One of our QAs tested this https://bb47m2.csb.app/ in his PC with **Windows10** and **Chrome114** and the result is nearly the same as my previous screenshots.
![Modal Open](https://github.com/Sage/carbon/assets/90848080/7cf5d028-175c-4b72-b521-16c494456647)

And the PC that I used also had Windows10 and Chrome114. Thank you!

**Comment by robinzigmond** [comment]
Thanks @JinCoreana and sorry for the delay in coming back on this!

Having played around some more I can now confirm - your `aria-hidden` sandbox example does work with Windows Speech Recognition when using Chrome. However it does not when using Edge (which is what I was initially testing it with) - which explains why I was seeing a different result. I'm surprised by this as I'd thought modern Edge was basically a copy of Chrome - I guess they must buld the accessibility tree slightly differently?

I don't know if it's worth doing the fix if it only fixes things for one browser (I haven't yet tried Firefox to see what does and doesn't work there with Windows speech recognition). @tempertemper I wonder if you have any thoughts on this?
