### ISSUE TITLE
No focus on FlatTable if we are in a sidebar with Search

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#6225]
### Current behaviour

When we are in a sidebar component, when i want to use tab keyboard to move into the component, i cannot reach the Flat Table if i have my search component above.

### Expected behaviour

I want to reach the FlatTable after press tab key if the search had the focus

### CodeSandbox or Storybook URL

https://codesandbox.io/s/happy-mccarthy-wf6txy

### JIRA Ticket (Sage Only)

SBS-52110

### Carbon Version

119.8.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-6088

**Comment by edleeks87** [comment]
This isn't related to FlatTable but due to the fact that the Search has a button that appears when the input has focus but disappears when it is blurred and there is no value, the browser will then try to focus this button next and when it can't find it place focus on the body. I've raised (an issue)[https://github.com/Sage/design-system/issues/23] about this pattern with the DS and I believe there will be a refactor of the component to only support either a search with button or without to avoid this.

https://codesandbox.io/s/elegant-scooby-q9hlh3 -- example of it working without button
