### ISSUE TITLE
Pager header not displayed correctly with Pod

### ISSUE THREAD

**Issue by hagad** [Sage/carbon#6308]
### Current behaviour

The is an issue with Pager if we want to display it with the Pod component. 
See the expected design

### Expected behaviour

The expected design : 
<img width="931" alt="Capture d’écran 2023-09-08 à 14 19 33" src="https://github.com/Sage/carbon/assets/17086956/5e417faf-cd14-48b5-902e-dc8c6585056b">

### CodeSandbox or Storybook URL

https://codesandbox.io/s/nostalgic-star-5vlw5m?file=/src/App.js

### Carbon Version

119.10.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
Hi @hagad as far as we can tell the code sandbox looks correct compared to the design you've provided. Is there a specific issue you would be able to tell us about?

**Comment by hagad** [comment]
Hi @tomdavies73 the issue is that the pager is not closed as expected. 
It should like the expected design I provided.

**Comment by Parsium** [comment]
It appears the top border on `Pager` is currently missing, likely because we are accounting for when `Pager` is used with `FlatTable`, where we don't want a top border with rounded corners:

![Screenshot 2023-09-19 at 11 26 17](https://github.com/Sage/carbon/assets/18368713/43067942-6b6e-4a07-9501-042e4e5cb446)

I will raise a ticket this so `Pager` can be used elsewhere without `FlatTable`

**Comment by Parsium** [comment]
Looking at the Design System documentation on their Pagination component, there doesn't seem to be any guidance around using the component separately to a table. I will raise this as an issue with them before we make this change.
