### ISSUE TITLE
Add tabIndex and ref props to Typography

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#6321]
### Desired behaviour

A11y sometimes require us to programatically focus content, such as error headings. To do so we need to be able to pass a ref to Typography and set a `tabIndex` to make it focusable. 

While a `Box` or `div` wrapper is a workaround it makes testing more awkward due to needing to set `data-role` or disable lint rules around direct node access in React Testing Library.

### Current behaviour

`Typography` does not support passing a ref or setting `tabIndex`.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
FE-6220

**Comment by nineteen88** [comment]
Hi @johnb-sage @tempertemper, I just wanted to check in with you both on this after I've been looking into the issue. I started to write a Story for this and it got me thinking, what are the actual use cases of this? Because exposing ref seems to be quite a heavy handed approach on the surface, so I just want to understand the end goals here in case there is a better alternative.

**Comment by johnb-sage** [comment]
Hi @nineteen88 
This requirement has come about from a11y recommendations for focusing content on error pages so screen readers correctly announce key information.

**Comment by tempertemper** [comment]
For an error heading I would usually place focus on the message component container rather than its heading. I'd label the container *using* the header though; something like:

```html
<div class="message-component" aria-labelledby="messageComponentHeader" tabindex="-1">
    <h2 id="messageComponentHeader">There is a problem (or whatever the message component's header is)</h2>
    <!-- Rest of the message component goes here -->
</div>
```

Note, I've used `tabindex="-1"` rather than `tabindex="0"` so that users can't put focus back on the non-interactive element.

And if you want to be really fancy you could remove the `tabindex` attribute completely once it loses focus (unless an error is triggered again, of course, in which case you'd add it back) as it is still able to be clicked by a mouse, although this isn't a big deal as it doesn't have a focus indicator.

It's not a huge deal from a user's point of view if the heading gets focus rather than the container, but it's consistent with how dialogs should work (where the screen reader user needs to be told they're on a dialog, so the `aria-labelledby` pointing at the heading deffo is a requirement). Finally, and what do I know about Carbon, but it might even be simpler to implement as you'd have to add the prop to all typography elements. And allowing devs to, with the best intentions, put focus on any typography element feels a bit weird.

**Comment by johnb-sage** [comment]
@tempertemper Here's a ticket advising focusing the error heading (check the comments): https://jira.sage.com/browse/SBS-55708

I'm not sure weather we were actively avoiding the entire error page from being read out.

**Comment by nineteen88** [comment]
Hi @johnb-sage - are there any foreseen issues with Martin's solution? It feels like the better way of solving this to me but I could of course be wrong. Let me know.

**Comment by johnb-sage** [comment]
@nineteen88 Not sure, seems like we're getting conflicting guidance. @tempertemper have you had a chance to review the ticket referenced? Should we change how we draw attention to the error?

**Comment by tempertemper** [comment]
Ah I see that Chris M mentioned to put the focus on the heading in the [Jira ticket](https://jira.sage.com/browse/SBS-55708). It's a totally valid approach, but the container (immediately before the heading) is slightly more consistent with modal focus, message focus, etc. Plus it means no changes are needed to the typography components, I think, if we can already put focus on the box component.

Another thing… I assumed you were talking about error validation rather than full screen errors. Another approach here would be to reset focus to the page itself. This is the usual behaviour when the user is taken to a new page, which is what this essentially is.

A keyboard user would then tab to the skip link to jump past the nav to the main content area, and a keyboard user would hear the `<title>`, which would contain the error heading, then use a keyboard shortcut to jump to the main content (either to the first heading or to the main landmark).

The approach where we'd place focus on the main chunk of content on the page is still valid and, probably, more convenient. But would it be *expected*? I'm genuinely not sure. Might be that user testing can inform us of the correct approach to take:

1. Place focus on an on-page element
2. Place focus on the page itself.

Either approach is valid.

I think this is also something we should take to the Design System so that the general approach is consistent.

**Comment by v99rly** [comment]
Happy to add this to the DS. Leave it with me and il get a ticket created.

**Comment by nineteen88** [comment]
@tempertemper @johnb-sage Both happy for me to close this issue then?

**Comment by johnb-sage** [comment]
@nineteen88 Can it be put on hold for now? We might be back here depending on what the Design System decides.

**Comment by nicktitchmarsh** [comment]
I'm closing this for now, it can be reopened if the work is necessary
