### ISSUE TITLE
AnchorNavigation: jump-links don't seem to be working

### ISSUE THREAD

**Issue by damienrobson-sage** [Sage/carbon#6437]
### Current behaviour

When clicking the section titles in the navigation section, the screen no longer scrolls to focus the relevant reference.

### Expected behaviour

When clicking the section titles in the navigation section, the screen should scroll the relevant reference into focus.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/nice-johnson-6mpsdr?file=/src/index.js

### Carbon Version

119.11.0

### Design Tokens Version

4.23.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
I don't believe there's an issue here - the props are passed/consumed incorrectly between the components in the sandbox example.

I've fixed it [here](https://codesandbox.io/s/fast-leftpad-klxj8p?file=/src/App.js) but interestingly after first doing that observed the crash raised at https://github.com/Sage/carbon/issues/6344. But then on refreshing the sandbox I was no longer able to reproduce.

Regardless, I don't think there's an actual issue here regarding jump-links simply "not working" when props are passed correctly. Please close the issue if you agree.
