### ISSUE TITLE
Ability to use Tile Select as a link.

### ISSUE THREAD

**Issue by JohnOxleySage** [Sage/carbon#6572]
### Desired behaviour

We have a requirement to have a component that looks like a Tile Select but acts like a link. I've gotten this working by adding a redirect in the onChange but voiceover is reading these as a checkbox. For this to be accessible we need to display the href and to have the input type be link rather than checkbox. 

### Current behaviour

Tile select works as a link but looks like a checkbox to a screenreader.

### Suggested Solution

Add a prop for href that when present sets the input type to be a link and when clicked redirects to the href given. Or create a new TileLink component to cover this specific scenario.

### CodeSandbox or Storybook URL

https://codesandbox.io/p/sandbox/gallant-heisenberg-2gtzd9

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @JohnOxleySage 👋🏼 Looking at this triage, we shared concerns about this since `TileSelect` wasn't designed to be a link, but act like a radio button in a group, so a user can select one tile out of a group of tiles.

If you need a container-like component that acts like an `a` anchor tag, would the `Card` component work instead? We allow[ rendering `Card` as an anchor via its `interactive` prop.](https://carbon.sage.com/?path=/docs/card--interactive)

**Comment by edleeks87** [comment]
We no longer support this via the `interactive` prop it is now `onClick` to render as a button or `href` to render as an anchor
