### ISSUE TITLE
Profile cant receive mb

### ISSUE THREAD

**Issue by emgosa** [Sage/carbon#6622]
### Description

I am doing a selector, which includes a checkbox and a profile.
Cant align profile with checkbox.
Neither using a box with profile inside.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-jh1lf5?file=src%2FApp.tsx

### Suggested solution

Integrate components Checkbox in Profile.

### Carbon version

latest

### Design tokens version

4.29.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
Hi @emgosa yeah, this is an issue with the type interface on `Profile`, which should extend `MarginProps`. Margins are still applied, but unfortunately there is still a type error.

Thanks for sending over that template - I'd recommend using a different pattern though to achieve alignment. Instead of passing the `Portrait` component as a node via the `label` prop on `Checkbox` I'd keep the components separate and just use the same string value that you pass to `name` on `Profile` as the `aria-label` prop on `Checkbox `. After adding some flex attributes to the `Box` above in the DOM, they can align quite nicely (sandbox here: https://stackblitz.com/edit/parsium-carbon-starter-ikzxfr?file=src%2FApp.tsx)
