### ISSUE TITLE
`Select` component to have a better truncated format

### ISSUE THREAD

**Issue by JinCoreana** [Sage/carbon#6641]
### Description

Currently, if content in `Select` component overflows, the content gets cropped without ...
Having elipses in this case would enhance accessibility.

<img width="270" alt="Screenshot 2024-03-22 at 12 10 34" src="https://github.com/Sage/carbon/assets/90848080/de8e31ba-d0a2-4db4-bd63-a4511dfbb01a">

### Suggested solution

Please add elipses when the full content needs to be cropped due to the limited width.

<img width="333" alt="Screenshot 2024-03-22 at 12 11 03" src="https://github.com/Sage/carbon/assets/90848080/bd232ffb-39e6-4ff0-888a-24e54c3eecbb">

### Demo URL

https://stackblitz.com/edit/parsium-carbon-starter-w9s2xj?file=src%2FApp.tsx,src%2Fmain.tsx

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
@tempertemper would you be able to review this for us please? Is there any accessibility concerns with us adding truncation to the input value here?

**Comment by tempertemper** [comment]
This is a case where I think truncation is a valid approach. First up, this is an edge case as the designer would probably take care of the label length or, if a whole sentence was needed for user understanding, a content type other than select could be used (maybe radios).

But here's why I think it's okay in the hopefully unlikely scenario there's too much text for the box:
- It user-chosen input, where the full label was (and always is) available inside the dropdown, where (I assume) the label wraps onto two or more lines
- As long as the box is wide enough there would be less chance of two options with identical wording at the start of the string clashing (plus clever content design can usually avoid this)
- If it were to wrap rather than truncate, increasing the box size could be jarring or even disorienting for users

**Comment by edleeks87** [comment]
Great thanks @tempertemper I'll raise a ticket for this now

**Comment by edleeks87** [comment]
FE-6409
