### ISSUE TITLE
Invalid ARIA attribute value when using Select with object as value

### ISSUE THREAD

**Issue by liambellsage** [Sage/carbon#6673]
### Description

When using the Select component with object as value as per the [docs](https://carbon.sage.com/?path=/docs/select--docs#with-object-as-value) an axe issue exists after changing the value in the Select

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-ztqhvg?file=src%2FApp.tsx

### Steps to reproduce

Scan the a couple of times with axe tools until the number of issues are consistent (I see 14 issues on the first scan and 5 on subsequent scans)

Next change the selected item in the Select element a couple of times.

Now run another scan with axe. There will be a new issue:
`Invalid ARIA attribute value: aria-activedescendant="(SOME GUID)"`

### Carbon version

127.0.0

### Relevant browsers

Chrome

### Relevant OSs

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6432

**Comment by nuria1110** [comment]
Closing as this issue was fixed in [v131.0.1](https://github.com/Sage/carbon/releases/tag/v131.0.1), although unfortunately it seems as our Stackblitz template is not updating to the latest version, therefore the sandbox provided is using v125.9.1 (from package-lock.json). Here is the updated [Stackblitz demo](https://stackblitz.com/edit/parsium-carbon-starter-kzvaw4?file=src%2FApp.tsx) using the version where this issue was fixed. Please let us know if you are still experiencing issues with this component.
