### ISSUE TITLE
FlexTileContainer cuts off content

### ISSUE THREAD

**Issue by IrynaD26** [Sage/carbon#6695]
### Description

We are using `FlexTileContainer`  and `FlexTileCell`. There is a button inside `FlexTileCell`. When the button is focused, its `box-shadow` is cut off by `FlexTileContainer`.  This happens because `FlexTileContainer` has `overflow: hidden` by default.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-vbf2yg?file=src%2FApp.tsx

### Steps to reproduce

1. Open the link 
2. See that the button inside the responsive tile is focused **(If it's not focused, focus it manually**)
3. See that the button's box-shadow is cut off by the tile

### JIRA ticket numbers (Sage only)

SBS-89592

### Suggested solution

The possibility to turn off / on `overflow: hidden`. Not sure if it's the best solution and if it doesn't break the  tile layout. This solution needs to be tested properly.

### Carbon version

132.2.0

### Design tokens version

4.34.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS, Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-6540

**Comment by nineteen88** [comment]
We're going to close this issue due to the `overflow: hidden` being required in order to hide the horizontal lines within `FlexTileContainer`. Therefore it is not advisable to allow toggling it off, as this will create other issues and isn't an actual fix to the issue at hand. We can only suggest adding margin to the button to account for the focus border.
