### ISSUE TITLE
Responsive/Flex Progress Bar Length in ProgressTracker

### ISSUE THREAD

**Issue by adamfsage** [Sage/carbon#6760]
### Description

As a developer using carbon, I'd like the option to make the progress bar length in ProgressTracker automatically size to the size of the responsive tile. The designers have expressed an interest in having the bar length stretch to the size of the tile but this is not possible currently 

<img width="397" alt="image" src="https://github.com/Sage/carbon/assets/155455220/a61a457f-f7df-480d-ad61-8470a120fe35">

vs

<img width="308" alt="image" src="https://github.com/Sage/carbon/assets/155455220/5ea57462-895f-48ee-ad49-602e7a1198e5">

### Suggested solution

Add a prop to toggle between fixed length and flex length for the progress bar in ProgressTracker

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nuria1110** [comment]
The ProgressTracker has a `length` prop which accepts any valid css property to set the width of the progress bar, see our [docs](https://carbon.sage.com/?path=/docs/progress-tracker--docs#custom-bar-length) for an example. You can set this prop to "100%" so that the bar length stretches to the full width of its container. 

Please let us know if this is not what you were looking for and we can raise an enhancement ticket.

**Comment by adamfsage** [comment]
There's an issue with the progress bar being slightly too big when width is 100%. I've raised it here: https://github.com/Sage/carbon/issues/6779

I must've assumed using "100%" wasn't intended behaviour when I saw this, and tried to set length via pixels

I'm happy for this ticket to be closed
