### ISSUE TITLE
Return focus on the button which opened Confirm modal

### ISSUE THREAD

**Issue by foxyd-sage** [Sage/carbon#6870]
### Description

I using this Confirm modal component https://carbon.sage.com/?path=/docs/confirm--docs.
When I open the modal and clicked the cancel or confirm buttons returns focus to the document body, not on the button which opening this modal.
So, when I closing the Confirm modal, I expecting that focus will be on the button which openning this modal. 
[This contradicts the guidelines recommended for Modals](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/)

### Reproduction

https://stackblitz.com/edit/confirm-focus-on-close?file=src%2FApp.tsx

### Steps to reproduce

Better to use Tab and Space for reproducing.

1) Click to "Open Confirm" button.
2) In the Confirm modal click Cancel button.
3) Use Tab on the keyboard to focus on the "Open Confirm" button.

### JIRA ticket numbers (Sage only)

SBS-103263

### Carbon version

138.1.0

### Design tokens version

4.34.0

### Relevant browsers

Chrome

### Relevant OSs

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
It appears there is a consistency issue with refocusing the opening button upon closing the modal. While [it works when the Escape key is pressed](https://stackblitz.com/edit/confirm-focus-on-close), clicking the cancel or confirm buttons returns focus to the document body rather than the opening button. This will need addressing for all the modal-based components in Carbon.
