### ISSUE TITLE
Allow 1 row height for TextArea component

### ISSUE THREAD

**Issue by harryharford** [Sage/carbon#6954]
### Description

On https://github.com/Sage/carbon/issues/6860 a change was made to make minHeight configurable for the TextArea component, this goes some way to allowing the component to align with other similar text inputs. 

Unfortunately, with the `rows` prop set to `1` - the minimum number of text rows is still 2. 
![image](https://github.com/user-attachments/assets/11d7402e-5099-4256-abcd-0c2680624aea)

This means the component can still not easily be used alongside others like TextBox due to the height and rows difference. 

### Suggested solution

Allow 1 row of text in the TextArea component. After 1 row the field could expand or be scrollable.

### Additional context

@ljemmo Has confirmed that this requirement would be fine as long as the a default is set.

Worth noting that since `rows: 1` is already supported but restricts to a 2 row minimum, a different value may need to be used to actually support just 1 row without being a breaking change for those who have already implemented with 1.  

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nuria1110** [comment]
FE-6811

**Comment by harpalsingh** [comment]
Just to add, had this discussion around this component with DS @ljemmo and the component itself has a min-height of 64px to ensure it is clear to users it is different from a Textbox visually, since it also has different keyboard behaviours and allows it be clear there is multi-line content as well as a easier time to use the scroll/resize if needed. Designs that use this component at the small size will be updated to reflect this.
