### ISSUE TITLE
Multi Action Button still not always working for screenreader despite being tabbable - serious

### ISSUE THREAD

**Issue by adamfsage** [Sage/carbon#7054]
### Description

When I click on dynamic shortcut button in home.ui (eg. Go to Accounting, Go to Payroll...) with a screenreader, it should focus on the options instead of ignoring it and going through the rest of the DOM.

Similar to this issue [here](https://github.com/Sage/carbon/issues/7005), I have tried on updated carbon but this still does not work despite being tabbable

https://github.com/user-attachments/assets/7905501d-935c-48d2-addd-995124a14018

### Reproduction

https://carbon.sage.com/?path=/story/multi-action-button--button-types

### Steps to reproduce

Open screenreader, select multi-action button, click to open and then go to next element

### JIRA ticket numbers (Sage only)

SBS-113601

### Carbon version

144.4.0

### Design tokens version

4.34.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by hrrcox** [comment]
Using VoiceOver in Safari, select multi action button with VO commands (ctrl+option) + Space, expected behaviour would be that button popover opens and focus is taken to the popover. VO+left would then move through the child items within the popover.

Current behaviour is that VO+space opens the popover, but unable to reach child items using VO+left, moves onto next item beyond the popover. 

Tested on Carbon V144.4.0 in Safari with VO and in Firefox with NVDA

**Comment by nicktitchmarsh** [comment]
FE-6890
