### ISSUE TITLE
StepFlow does not accept help or HelpID Props.

### ISSUE THREAD

**Issue by ConnollyM** [Sage/carbon#7095]
### Description

The StepFlow component when passed into a dialog title (as per you example implementation [Example implementation with title node](https://carbon.sage.com/?path=/story/step-flow--example-implementation-with-title-node) does not allow for help or helpId props to be passed.

### Suggested solution

Allow help and helpId props to be passed to the step flow component so that a help icon can be rendered, as the regular dialog or heading components do. This will allow users of the system to be able to click a link to take them to the products help system, in line with the other areas of the program.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
I believe the DS want to move away from using `Help` (mainly due to the use of tooltips that is can support) so we're reluctant to bake in support for it into anymore components. You should still be able to compose it with the existing props, `StepFlow` currently implicitly supports `aria-describedby` (we'll ensure it's explicitly added to the interface asap) so there shouldn't be any accessibility issues with the approach. If there are let us know and we'll revisit the recommendation. FYI @ljemmo and @harpalsingh 

```
const titleNode = (
    <Box display="flex" alignItems="center">
      <Icon type="bin" />
      <StepFlowTitle titleString={stepTitles[step - 1]} />
      <Help href="#" helpId="foo" tooltipId="bar">HELP ME</Help>
    </Box>
  );
  
   <StepFlow
          category="Main goal"
          title={titleNode}
          currentStep={step as Steps}
          totalSteps={highestStep}
          ref={stepFlowHandle}
          showProgressIndicator
          onDismiss={() => setIsOpen(false)}
          mb="20px"
          titleVariant="h2"
          aria-describedby="foo bar"
   />
 ```

**Comment by tomdavies73** [comment]
@ConnollyM, please see the suggested solution above. What you would like to achieve is currently possible whilst using a compositional approach via the `title` prop which accepts a node. 

We will also add the `aria-describedby` attribute to the `StepFlow`'s prop table so it is properly documented.

**Comment by tomdavies73** [comment]
FE-7103 - ticket to document the relevant aria props

**Comment by nicktitchmarsh** [comment]
We will add documentation regarding the `aria` props but won't be making any code changes for this
